export const BUNNER = `\
// WARN: file has been generated by gameface/scripts/migration-cli tool. \
Please, don't change it manually.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
`
