from personal_missions_constants import PROGRESS_TEMPLATE, CONDITION_ICON, VISIBLE_SCOPE, CRIT_TYPES
_config = {b'lightTank_shots_easy': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                       b'config': {b'goal': 2, 
                                                   b'isMain': True, 
                                                   b'isAward': True, 
                                                   b'isCumulative': True, 
                                                   b'visibleScope': [
                                                                   VISIBLE_SCOPE.BATTLE], 
                                                   b'params': {b'attackReasons': [
                                                                                b'shot']}}, 
                                       b'description': b'lightTank_shots_plural', 
                                       b'icon': (CONDITION_ICON.HIT)}}, 
   b'lightTank_shots_medium': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                         b'config': {b'goal': 4, 
                                                     b'isMain': True, 
                                                     b'isAward': True, 
                                                     b'isCumulative': True, 
                                                     b'visibleScope': [
                                                                     VISIBLE_SCOPE.BATTLE], 
                                                     b'params': {b'attackReasons': [
                                                                                  b'shot']}}, 
                                         b'description': b'lightTank_shots_plural', 
                                         b'icon': (CONDITION_ICON.HIT)}}, 
   b'lightTank_shots_hard': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                       b'config': {b'goal': 7, 
                                                   b'isMain': True, 
                                                   b'isAward': True, 
                                                   b'isCumulative': True, 
                                                   b'visibleScope': [
                                                                   VISIBLE_SCOPE.BATTLE], 
                                                   b'params': {b'attackReasons': [
                                                                                b'shot']}}, 
                                       b'description': b'lightTank_shots_plural', 
                                       b'icon': (CONDITION_ICON.HIT)}}, 
   b'lightTank_damage_easy': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                          b'config': {b'goal': 400, 
                                                      b'isMain': True, 
                                                      b'isAward': True, 
                                                      b'isCumulative': True, 
                                                      b'visibleScope': [
                                                                      VISIBLE_SCOPE.BATTLE]}, 
                                          b'description': b'lightTank_damage', 
                                          b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'lightTank_damage_medium': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                            b'config': {b'goal': 700, 
                                                        b'isMain': True, 
                                                        b'isAward': True, 
                                                        b'isCumulative': True, 
                                                        b'visibleScope': [
                                                                        VISIBLE_SCOPE.BATTLE]}, 
                                            b'description': b'lightTank_damage', 
                                            b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'lightTank_damage_hard': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                          b'config': {b'goal': 1100, 
                                                      b'isMain': True, 
                                                      b'isAward': True, 
                                                      b'isCumulative': True, 
                                                      b'visibleScope': [
                                                                      VISIBLE_SCOPE.BATTLE]}, 
                                          b'description': b'lightTank_damage', 
                                          b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'lightTank_kills_easy': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                        b'config': {b'goal': 1, 
                                                    b'isMain': True, 
                                                    b'isAward': True, 
                                                    b'isCumulative': True, 
                                                    b'visibleScope': [
                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                        b'description': b'lightTank_kills', 
                                        b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'lightTank_kills_medium': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                          b'config': {b'goal': 2, 
                                                      b'isMain': True, 
                                                      b'isAward': True, 
                                                      b'isCumulative': True, 
                                                      b'visibleScope': [
                                                                      VISIBLE_SCOPE.BATTLE]}, 
                                          b'description': b'lightTank_kills', 
                                          b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'lightTank_kills_hard': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                        b'config': {b'goal': 3, 
                                                    b'isMain': True, 
                                                    b'isAward': True, 
                                                    b'isCumulative': True, 
                                                    b'visibleScope': [
                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                        b'description': b'lightTank_kills', 
                                        b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'lightTank_critsTracks_easy': {b'crits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                              b'config': {b'goal': 1, 
                                                          b'isMain': True, 
                                                          b'isAward': True, 
                                                          b'isCumulative': True, 
                                                          b'visibleScope': [
                                                                          VISIBLE_SCOPE.BATTLE], 
                                                          b'params': {b'critTypes': (CRIT_TYPES.DESTROYED_TRACKS)}}, 
                                              b'description': b'lightTank_critsTracks', 
                                              b'icon': (CONDITION_ICON.MODULE_CRIT)}}, 
   b'lightTank_critsTracks_medium': {b'crits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                b'config': {b'goal': 2, 
                                                            b'isMain': True, 
                                                            b'isAward': True, 
                                                            b'isCumulative': True, 
                                                            b'visibleScope': [
                                                                            VISIBLE_SCOPE.BATTLE], 
                                                            b'params': {b'critTypes': (CRIT_TYPES.DESTROYED_TRACKS)}}, 
                                                b'description': b'lightTank_critsTracks', 
                                                b'icon': (CONDITION_ICON.MODULE_CRIT)}}, 
   b'lightTank_critsTracks_hard': {b'crits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                              b'config': {b'goal': 3, 
                                                          b'isMain': True, 
                                                          b'isAward': True, 
                                                          b'isCumulative': True, 
                                                          b'visibleScope': [
                                                                          VISIBLE_SCOPE.BATTLE], 
                                                          b'params': {b'critTypes': (CRIT_TYPES.DESTROYED_TRACKS)}}, 
                                              b'description': b'lightTank_critsTracks', 
                                              b'icon': (CONDITION_ICON.MODULE_CRIT)}}, 
   b'mediumTank_shots_easy': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                        b'config': {b'goal': 3, 
                                                    b'isMain': True, 
                                                    b'isAward': True, 
                                                    b'isCumulative': True, 
                                                    b'visibleScope': [
                                                                    VISIBLE_SCOPE.BATTLE], 
                                                    b'params': {b'attackReasons': [
                                                                                 b'shot']}}, 
                                        b'description': b'mediumTank_shots_plural', 
                                        b'icon': (CONDITION_ICON.HIT)}}, 
   b'mediumTank_shots_medium': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                          b'config': {b'goal': 6, 
                                                      b'isMain': True, 
                                                      b'isAward': True, 
                                                      b'isCumulative': True, 
                                                      b'visibleScope': [
                                                                      VISIBLE_SCOPE.BATTLE], 
                                                      b'params': {b'attackReasons': [
                                                                                   b'shot']}}, 
                                          b'description': b'mediumTank_shots_plural', 
                                          b'icon': (CONDITION_ICON.HIT)}}, 
   b'mediumTank_shots_hard': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                        b'config': {b'goal': 9, 
                                                    b'isMain': True, 
                                                    b'isAward': True, 
                                                    b'isCumulative': True, 
                                                    b'visibleScope': [
                                                                    VISIBLE_SCOPE.BATTLE], 
                                                    b'params': {b'attackReasons': [
                                                                                 b'shot']}}, 
                                        b'description': b'mediumTank_shots_plural', 
                                        b'icon': (CONDITION_ICON.HIT)}}, 
   b'mediumTank_damage_easy': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                           b'config': {b'goal': 800, 
                                                       b'isMain': True, 
                                                       b'isAward': True, 
                                                       b'isCumulative': True, 
                                                       b'visibleScope': [
                                                                       VISIBLE_SCOPE.BATTLE]}, 
                                           b'description': b'mediumTank_damage', 
                                           b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'mediumTank_damage_medium': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                             b'config': {b'goal': 1300, 
                                                         b'isMain': True, 
                                                         b'isAward': True, 
                                                         b'isCumulative': True, 
                                                         b'visibleScope': [
                                                                         VISIBLE_SCOPE.BATTLE]}, 
                                             b'description': b'mediumTank_damage', 
                                             b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'mediumTank_damage_hard': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                           b'config': {b'goal': 2100, 
                                                       b'isMain': True, 
                                                       b'isAward': True, 
                                                       b'isCumulative': True, 
                                                       b'visibleScope': [
                                                                       VISIBLE_SCOPE.BATTLE]}, 
                                           b'description': b'mediumTank_damage', 
                                           b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'mediumTank_hits_easy': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                       b'config': {b'goal': 2, 
                                                   b'isMain': True, 
                                                   b'isAward': True, 
                                                   b'isCumulative': True, 
                                                   b'visibleScope': [
                                                                   VISIBLE_SCOPE.BATTLE], 
                                                   b'params': {b'uniqueTargetAndType': True}}, 
                                       b'description': b'mediumTank_hits', 
                                       b'icon': (CONDITION_ICON.HIT)}}, 
   b'mediumTank_hits_medium': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                         b'config': {b'goal': 4, 
                                                     b'isMain': True, 
                                                     b'isAward': True, 
                                                     b'isCumulative': True, 
                                                     b'visibleScope': [
                                                                     VISIBLE_SCOPE.BATTLE], 
                                                     b'params': {b'uniqueTargetAndType': True}}, 
                                         b'description': b'mediumTank_hits', 
                                         b'icon': (CONDITION_ICON.HIT)}}, 
   b'mediumTank_hits_hard': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                       b'config': {b'goal': 6, 
                                                   b'isMain': True, 
                                                   b'isAward': True, 
                                                   b'isCumulative': True, 
                                                   b'visibleScope': [
                                                                   VISIBLE_SCOPE.BATTLE], 
                                                   b'params': {b'uniqueTargetAndType': True}}, 
                                       b'description': b'mediumTank_hits', 
                                       b'icon': (CONDITION_ICON.HIT)}}, 
   b'mediumTank_hitsDiversity_easy': {b'hitsDiversity': {b'type': (PROGRESS_TEMPLATE.COUNTER), 
                                                         b'config': {b'uniqueGoal': 2, 
                                                                     b'totalGoal': 2, 
                                                                     b'isMain': True, 
                                                                     b'isAward': True, 
                                                                     b'isCumulative': True, 
                                                                     b'visibleScope': [
                                                                                     VISIBLE_SCOPE.BATTLE]}, 
                                                         b'description': b'mediumTank_hitsDiversity', 
                                                         b'icon': (CONDITION_ICON.HURT_VEHICLES)}}, 
   b'mediumTank_hitsDiversity_medium': {b'hitsDiversity': {b'type': (PROGRESS_TEMPLATE.COUNTER), 
                                                           b'config': {b'uniqueGoal': 3, 
                                                                       b'totalGoal': 3, 
                                                                       b'isMain': True, 
                                                                       b'isAward': True, 
                                                                       b'isCumulative': True, 
                                                                       b'visibleScope': [
                                                                                       VISIBLE_SCOPE.BATTLE]}, 
                                                           b'description': b'mediumTank_hitsDiversity', 
                                                           b'icon': (CONDITION_ICON.HURT_VEHICLES)}}, 
   b'mediumTank_kills_easy': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                         b'config': {b'goal': 1, 
                                                     b'isMain': True, 
                                                     b'isAward': True, 
                                                     b'isCumulative': True, 
                                                     b'visibleScope': [
                                                                     VISIBLE_SCOPE.BATTLE]}, 
                                         b'description': b'mediumTank_kills', 
                                         b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'mediumTank_kills_medium': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                           b'config': {b'goal': 2, 
                                                       b'isMain': True, 
                                                       b'isAward': True, 
                                                       b'isCumulative': True, 
                                                       b'visibleScope': [
                                                                       VISIBLE_SCOPE.BATTLE]}, 
                                           b'description': b'mediumTank_kills', 
                                           b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'mediumTank_kills_hard': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                         b'config': {b'goal': 3, 
                                                     b'isMain': True, 
                                                     b'isAward': True, 
                                                     b'isCumulative': True, 
                                                     b'visibleScope': [
                                                                     VISIBLE_SCOPE.BATTLE]}, 
                                         b'description': b'mediumTank_kills', 
                                         b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'mediumTank_killsDiversity_medium': {b'killsDiversity': {b'type': (PROGRESS_TEMPLATE.COUNTER), 
                                                             b'config': {b'uniqueGoal': 2, 
                                                                         b'totalGoal': 2, 
                                                                         b'isMain': True, 
                                                                         b'isAward': True, 
                                                                         b'isCumulative': True, 
                                                                         b'visibleScope': [
                                                                                         VISIBLE_SCOPE.BATTLE]}, 
                                                             b'description': b'mediumTank_killsDiversity', 
                                                             b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'mediumTank_critsTracks_easy': {b'crits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                               b'config': {b'goal': 1, 
                                                           b'isMain': True, 
                                                           b'isAward': True, 
                                                           b'isCumulative': True, 
                                                           b'visibleScope': [
                                                                           VISIBLE_SCOPE.BATTLE], 
                                                           b'params': {b'critTypes': (CRIT_TYPES.DESTROYED_TRACKS)}}, 
                                               b'description': b'mediumTank_critsTracks', 
                                               b'icon': (CONDITION_ICON.MODULE_CRIT)}}, 
   b'mediumTank_critsTracks_medium': {b'crits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                 b'config': {b'goal': 2, 
                                                             b'isMain': True, 
                                                             b'isAward': True, 
                                                             b'isCumulative': True, 
                                                             b'visibleScope': [
                                                                             VISIBLE_SCOPE.BATTLE], 
                                                             b'params': {b'critTypes': (CRIT_TYPES.DESTROYED_TRACKS)}}, 
                                                 b'description': b'mediumTank_critsTracks', 
                                                 b'icon': (CONDITION_ICON.MODULE_CRIT)}}, 
   b'mediumTank_critsTracks_hard': {b'crits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                               b'config': {b'goal': 3, 
                                                           b'isMain': True, 
                                                           b'isAward': True, 
                                                           b'isCumulative': True, 
                                                           b'visibleScope': [
                                                                           VISIBLE_SCOPE.BATTLE], 
                                                           b'params': {b'critTypes': (CRIT_TYPES.DESTROYED_TRACKS)}}, 
                                               b'description': b'mediumTank_critsTracks', 
                                               b'icon': (CONDITION_ICON.MODULE_CRIT)}}, 
   b'heavyTank_kills_easy': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                        b'config': {b'goal': 1, 
                                                    b'isMain': True, 
                                                    b'isAward': True, 
                                                    b'isCumulative': True, 
                                                    b'visibleScope': [
                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                        b'description': b'heavyTank_kills', 
                                        b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'heavyTank_kills_medium': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                          b'config': {b'goal': 2, 
                                                      b'isMain': True, 
                                                      b'isAward': True, 
                                                      b'isCumulative': True, 
                                                      b'visibleScope': [
                                                                      VISIBLE_SCOPE.BATTLE]}, 
                                          b'description': b'heavyTank_kills', 
                                          b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'heavyTank_kills_hard': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                        b'config': {b'goal': 3, 
                                                    b'isMain': True, 
                                                    b'isAward': True, 
                                                    b'isCumulative': True, 
                                                    b'visibleScope': [
                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                        b'description': b'heavyTank_kills', 
                                        b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'heavyTank_killsDiversity_medium': {b'killsDiversity': {b'type': (PROGRESS_TEMPLATE.COUNTER), 
                                                            b'config': {b'uniqueGoal': 2, 
                                                                        b'totalGoal': 2, 
                                                                        b'isMain': True, 
                                                                        b'isAward': True, 
                                                                        b'isCumulative': True, 
                                                                        b'visibleScope': [
                                                                                        VISIBLE_SCOPE.BATTLE]}, 
                                                            b'description': b'heavyTank_killsDiversity', 
                                                            b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'heavyTank_damage_easy': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                          b'config': {b'goal': 800, 
                                                      b'isMain': True, 
                                                      b'isAward': True, 
                                                      b'isCumulative': True, 
                                                      b'visibleScope': [
                                                                      VISIBLE_SCOPE.BATTLE]}, 
                                          b'description': b'heavyTank_damage', 
                                          b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'heavyTank_damage_medium': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                            b'config': {b'goal': 1400, 
                                                        b'isMain': True, 
                                                        b'isAward': True, 
                                                        b'isCumulative': True, 
                                                        b'visibleScope': [
                                                                        VISIBLE_SCOPE.BATTLE]}, 
                                            b'description': b'heavyTank_damage', 
                                            b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'heavyTank_damage_hard': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                          b'config': {b'goal': 2300, 
                                                      b'isMain': True, 
                                                      b'isAward': True, 
                                                      b'isCumulative': True, 
                                                      b'visibleScope': [
                                                                      VISIBLE_SCOPE.BATTLE]}, 
                                          b'description': b'heavyTank_damage', 
                                          b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'heavyTank_damageDealtReceivedAndBlocked_easy': {b'damageDealtReceivedAndBlocked': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                                                        b'config': {b'goal': 2000, 
                                                                                                    b'isMain': True, 
                                                                                                    b'isAward': True, 
                                                                                                    b'isCumulative': True, 
                                                                                                    b'visibleScope': [
                                                                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                                                                        b'description': b'heavyTank_damageDealtReceivedAndBlocked', 
                                                                                        b'icon': (CONDITION_ICON.FOLDER)}}, 
   b'heavyTank_damageDealtReceivedAndBlocked_medium': {b'damageDealtReceivedAndBlocked': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                                                          b'config': {b'goal': 3500, 
                                                                                                      b'isMain': True, 
                                                                                                      b'isAward': True, 
                                                                                                      b'isCumulative': True, 
                                                                                                      b'visibleScope': [
                                                                                                                      VISIBLE_SCOPE.BATTLE]}, 
                                                                                          b'description': b'heavyTank_damageDealtReceivedAndBlocked', 
                                                                                          b'icon': (CONDITION_ICON.FOLDER)}}, 
   b'heavyTank_damageDealtReceivedAndBlocked_hard': {b'damageDealtReceivedAndBlocked': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                                                        b'config': {b'goal': 5750, 
                                                                                                    b'isMain': True, 
                                                                                                    b'isAward': True, 
                                                                                                    b'isCumulative': True, 
                                                                                                    b'visibleScope': [
                                                                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                                                                        b'description': b'heavyTank_damageDealtReceivedAndBlocked', 
                                                                                        b'icon': (CONDITION_ICON.FOLDER)}}, 
   b'ATSPG_damage_easy': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                      b'config': {b'goal': 900, 
                                                  b'isMain': True, 
                                                  b'isAward': True, 
                                                  b'isCumulative': True, 
                                                  b'visibleScope': [
                                                                  VISIBLE_SCOPE.BATTLE]}, 
                                      b'description': b'AT_SPG_damage', 
                                      b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'ATSPG_damage_medium': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                        b'config': {b'goal': 1500, 
                                                    b'isMain': True, 
                                                    b'isAward': True, 
                                                    b'isCumulative': True, 
                                                    b'visibleScope': [
                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                        b'description': b'AT_SPG_damage', 
                                        b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'ATSPG_damage_hard': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                      b'config': {b'goal': 2400, 
                                                  b'isMain': True, 
                                                  b'isAward': True, 
                                                  b'isCumulative': True, 
                                                  b'visibleScope': [
                                                                  VISIBLE_SCOPE.BATTLE]}, 
                                      b'description': b'AT_SPG_damage', 
                                      b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'ATSPG_hits_easy': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                  b'config': {b'goal': 2, 
                                              b'isMain': True, 
                                              b'isAward': True, 
                                              b'isCumulative': True, 
                                              b'visibleScope': [
                                                              VISIBLE_SCOPE.BATTLE], 
                                              b'params': {b'uniqueTargetAndType': True}}, 
                                  b'description': b'AT_SPG_hits', 
                                  b'icon': (CONDITION_ICON.HIT)}}, 
   b'ATSPG_hits_medium': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                    b'config': {b'goal': 4, 
                                                b'isMain': True, 
                                                b'isAward': True, 
                                                b'isCumulative': True, 
                                                b'visibleScope': [
                                                                VISIBLE_SCOPE.BATTLE], 
                                                b'params': {b'uniqueTargetAndType': True}}, 
                                    b'description': b'AT_SPG_hits', 
                                    b'icon': (CONDITION_ICON.HIT)}}, 
   b'ATSPG_hits_hard': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                  b'config': {b'goal': 6, 
                                              b'isMain': True, 
                                              b'isAward': True, 
                                              b'isCumulative': True, 
                                              b'visibleScope': [
                                                              VISIBLE_SCOPE.BATTLE], 
                                              b'params': {b'uniqueTargetAndType': True}}, 
                                  b'description': b'AT_SPG_hits', 
                                  b'icon': (CONDITION_ICON.HIT)}}, 
   b'ATSPG_kills_easy': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                    b'config': {b'goal': 1, 
                                                b'isMain': True, 
                                                b'isAward': True, 
                                                b'isCumulative': True, 
                                                b'visibleScope': [
                                                                VISIBLE_SCOPE.BATTLE]}, 
                                    b'description': b'AT_SPG_kills', 
                                    b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'ATSPG_kills_medium': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                      b'config': {b'goal': 2, 
                                                  b'isMain': True, 
                                                  b'isAward': True, 
                                                  b'isCumulative': True, 
                                                  b'visibleScope': [
                                                                  VISIBLE_SCOPE.BATTLE]}, 
                                      b'description': b'AT_SPG_kills', 
                                      b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'ATSPG_kills_hard': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                    b'config': {b'goal': 3, 
                                                b'isMain': True, 
                                                b'isAward': True, 
                                                b'isCumulative': True, 
                                                b'visibleScope': [
                                                                VISIBLE_SCOPE.BATTLE]}, 
                                    b'description': b'AT_SPG_kills', 
                                    b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'ATSPG_piercingSeries_easy': {b'piercingSeries': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                      b'config': {b'goal': 2, 
                                                                  b'isMain': True, 
                                                                  b'isAward': True, 
                                                                  b'isCumulative': True, 
                                                                  b'visibleScope': [
                                                                                  VISIBLE_SCOPE.BATTLE]}, 
                                                      b'description': b'AT_SPG_piercingSeries_plural', 
                                                      b'icon': (CONDITION_ICON.HIT)}}, 
   b'ATSPG_piercingSeries_medium': {b'piercingSeries': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                        b'config': {b'goal': 4, 
                                                                    b'isMain': True, 
                                                                    b'isAward': True, 
                                                                    b'isCumulative': True, 
                                                                    b'visibleScope': [
                                                                                    VISIBLE_SCOPE.BATTLE]}, 
                                                        b'description': b'AT_SPG_piercingSeries_plural', 
                                                        b'icon': (CONDITION_ICON.HIT)}}, 
   b'ATSPG_piercingSeries_hard': {b'piercingSeries': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                                      b'config': {b'goal': 6, 
                                                                  b'isMain': True, 
                                                                  b'isAward': True, 
                                                                  b'isCumulative': True, 
                                                                  b'visibleScope': [
                                                                                  VISIBLE_SCOPE.BATTLE]}, 
                                                      b'description': b'AT_SPG_piercingSeries_plural', 
                                                      b'icon': (CONDITION_ICON.HIT)}}, 
   b'SPG_hits_easy': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                b'config': {b'goal': 4, 
                                            b'isMain': True, 
                                            b'isAward': True, 
                                            b'isCumulative': True, 
                                            b'visibleScope': [
                                                            VISIBLE_SCOPE.BATTLE]}, 
                                b'description': b'SPG_hits_plural', 
                                b'icon': (CONDITION_ICON.HIT)}}, 
   b'SPG_hits_medium': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                  b'config': {b'goal': 7, 
                                              b'isMain': True, 
                                              b'isAward': True, 
                                              b'isCumulative': True, 
                                              b'visibleScope': [
                                                              VISIBLE_SCOPE.BATTLE]}, 
                                  b'description': b'SPG_hits_plural', 
                                  b'icon': (CONDITION_ICON.HIT)}}, 
   b'SPG_hits_hard': {b'hits': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                b'config': {b'goal': 11, 
                                            b'isMain': True, 
                                            b'isAward': True, 
                                            b'isCumulative': True, 
                                            b'visibleScope': [
                                                            VISIBLE_SCOPE.BATTLE]}, 
                                b'description': b'SPG_hits_plural', 
                                b'icon': (CONDITION_ICON.HIT)}}, 
   b'SPG_damage_easy': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                    b'config': {b'goal': 600, 
                                                b'isMain': True, 
                                                b'isAward': True, 
                                                b'isCumulative': True, 
                                                b'visibleScope': [
                                                                VISIBLE_SCOPE.BATTLE]}, 
                                    b'description': b'SPG_damage', 
                                    b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'SPG_damage_medium': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                      b'config': {b'goal': 1100, 
                                                  b'isMain': True, 
                                                  b'isAward': True, 
                                                  b'isCumulative': True, 
                                                  b'visibleScope': [
                                                                  VISIBLE_SCOPE.BATTLE]}, 
                                      b'description': b'SPG_damage', 
                                      b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'SPG_damage_hard': {b'damage': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                    b'config': {b'goal': 1800, 
                                                b'isMain': True, 
                                                b'isAward': True, 
                                                b'isCumulative': True, 
                                                b'visibleScope': [
                                                                VISIBLE_SCOPE.BATTLE]}, 
                                    b'description': b'SPG_damage', 
                                    b'icon': (CONDITION_ICON.DAMAGE)}}, 
   b'SPG_kills_easy': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                  b'config': {b'goal': 1, 
                                              b'isMain': True, 
                                              b'isAward': True, 
                                              b'isCumulative': True, 
                                              b'visibleScope': [
                                                              VISIBLE_SCOPE.BATTLE]}, 
                                  b'description': b'SPG_kills', 
                                  b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'SPG_kills_medium': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                    b'config': {b'goal': 2, 
                                                b'isMain': True, 
                                                b'isAward': True, 
                                                b'isCumulative': True, 
                                                b'visibleScope': [
                                                                VISIBLE_SCOPE.BATTLE]}, 
                                    b'description': b'SPG_kills', 
                                    b'icon': (CONDITION_ICON.KILL_VEHICLES)}}, 
   b'SPG_kills_hard': {b'kills': {b'type': (PROGRESS_TEMPLATE.VALUE), 
                                  b'config': {b'goal': 3, 
                                              b'isMain': True, 
                                              b'isAward': True, 
                                              b'isCumulative': True, 
                                              b'visibleScope': [
                                                              VISIBLE_SCOPE.BATTLE]}, 
                                  b'description': b'SPG_kills', 
                                  b'icon': (CONDITION_ICON.KILL_VEHICLES)}}}

def getQuestConfig(questID):
    return _config.get(questID, {})


def getQuestInfo(questName):
    return questName.split(b'_')


def getQuestType(questName):
    return getQuestInfo(questName)[1]
