class TOOLTIPS_CONSTANTS(object):
    COMP7_SELECTABLE_REWARD = b'comp7SelectableReward'
    COMP7_SELECTOR_INFO = b'comp7SelectorInfo'
    COMP7_SELECTOR_UNAVAILABLE_INFO = b'comp7SelectorUnavailableInfo'
    COMP7_ROLE_SKILL_LOBBY_TOOLTIP = b'comp7RoleSkillLobbyTooltip'
    COMP7_CALENDAR_DAY_INFO = b'comp7CalendarDayInfo'
    COMP7_CALENDAR_DAY_EXTENDED_INFO = b'comp7CalendarDayExtendedInfo'
    COMP7_BATTLE_RESULTS_RATING_POINTS = b'comp7BattleResultsRatingPoints'
    TOURNAMENT_COMP7_BATTLE_RESULTS_RATING_POINTS = b'tournamentComp7BattleResultsRatingPoints'
    TRAINING_COMP7_BATTLE_RESULTS_RATING_POINTS = b'trainingComp7BattleResultsRatingPoints'
    COMP7_GIFT_TOKEN = b'comp7GiftToken'
    COMP7_LOBBY_SET = [COMP7_SELECTOR_INFO, COMP7_SELECTOR_UNAVAILABLE_INFO, COMP7_CALENDAR_DAY_INFO, 
     COMP7_CALENDAR_DAY_EXTENDED_INFO, COMP7_ROLE_SKILL_LOBBY_TOOLTIP, COMP7_SELECTABLE_REWARD, 
     COMP7_BATTLE_RESULTS_RATING_POINTS, TOURNAMENT_COMP7_BATTLE_RESULTS_RATING_POINTS, 
     TRAINING_COMP7_BATTLE_RESULTS_RATING_POINTS]
