class CUSTOMIZATION_CONSTS(object):
    HISTORICAL_TYPE = 0
    NON_HISTORICAL_TYPE = 1
    FANTASTICAL_TYPE = 2
    FILTER_GROUP_MAIN = 0
    FILTER_GROUP_HISTORICAL = 1
    FILTER_GROUP_EDITABLE = 2
