class GIFTSYTEM_CONSTANTS(object):
    PLAYER_BANNED = b'playerBanned'
    PLAYER_ALREADY_RECEIVED_GIFT = b'playerAlreadyReceivedGift'
    PLAYER_IN_BLACK_LIST = b'playerInBlackList'
    PLAYER_BLOCKED_REASONS = [PLAYER_BANNED, PLAYER_ALREADY_RECEIVED_GIFT, PLAYER_IN_BLACK_LIST]
