class SHELL_CALIBRATION_WIDGET_CONSTS(object):
    NO_BONUS = b'noBonus'
    DAMAGE_BONUS = b'damageBonus'
    PENETRATION_BONUS = b'penetrationBonus'
    SHELL_CALIBRATION_WIDGET_STATES = [NO_BONUS, DAMAGE_BONUS, PENETRATION_BONUS]
