# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def compile(*args: Any, **kwargs: Any) -> Any: ...

def enumerate(*args: Any, **kwargs: Any) -> Any: ...

def isinstance(*args: Any, **kwargs: Any) -> Any: ...

def open(arg0: Any, arg1: str) -> bool: ...

def pow(*args: Any, **kwargs: Any) -> Any: ...

@overload
def reload(arg0: Any) -> None: ...
@overload
def reload(arg0: Any, arg1: Any = ...) -> None: ...
@overload
def reload(arg0: Any, arg1: int = ...) -> None: ...
@overload
def reload(arg0: Any, arg1: str = ...) -> None: ...

def repr(*args: Any, **kwargs: Any) -> Any: ...

__dict__: Any
__import__: Any
apply: Any
basestring: Any
chr: Any
cmp: Any
copyright: Any
credits: Any
dict: Any
execfile: Any
exit: Any
filter: Any
help: Any
intern: Any
license: Any
long: Any
map: Any
max: Any
min: Any
object: Any
oct: Any
quit: Any
range: Any
raw_input: Any
reduce: Any
str: Any
unichr: Any
unicode: Any
unload: Any
xrange: Any
zip: Any
