# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def Dialect(*args: Any, **kwargs: Any) -> Any: ...

def Error(*args: Any, **kwargs: Any) -> Any: ...

def reader(*args: Any, **kwargs: Any) -> Any: ...

def register_dialect(*args: Any, **kwargs: Any) -> Any: ...

def writer(*args: Any, **kwargs: Any) -> Any: ...

QUOTE_ALL: Any
QUOTE_MINIMAL: Any
QUOTE_NONE: Any
QUOTE_NONNUMERIC: Any
__doc__: Any
__version__: Any
field_size_limit: Any
get_dialect: Any
list_dialects: Any
unregister_dialect: Any
