# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def COMError(*args: Any, **kwargs: Any) -> Any: ...

def FormatError(*args: Any, **kwargs: Any) -> Any: ...

def FreeLibrary(*args: Any, **kwargs: Any) -> Any: ...

def LoadLibrary(*args: Any, **kwargs: Any) -> Any: ...

def POINTER(*args: Any, **kwargs: Any) -> Any: ...

def PyObj_FromPtr(*args: Any, **kwargs: Any) -> Any: ...

def call_function(*args: Any, **kwargs: Any) -> Any: ...

def dlopen(*args: Any, **kwargs: Any) -> Any: ...

def set_conversion_mode(*args: Any, **kwargs: Any) -> Any: ...

def sizeof(*args: Any, **kwargs: Any) -> Any: ...

ArgumentError: Any
Array: Any
CFuncPtr: Any
FUNCFLAG_CDECL: Any
FUNCFLAG_PYTHONAPI: Any
FUNCFLAG_STDCALL: Any
FUNCFLAG_USE_ERRNO: Any
FUNCFLAG_USE_LASTERROR: Any
RTLD_GLOBAL: Any
RTLD_LOCAL: Any
Structure: Any
Union: Any
_Pointer: Any
_SimpleCData: Any
__version__: Any
_cast_addr: Any
_check_HRESULT: Any
_memmove_addr: Any
_memset_addr: Any
_pointer_type_cache: Any
_string_at_addr: Any
_wstring_at_addr: Any
addressof: Any
alignment: Any
byref: Any
get_errno: Any
get_last_error: Any
pointer: Any
resize: Final[int] = 6
set_errno: Any
set_last_error: Any
