# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def endwin(*args: Any, **kwargs: Any) -> Any: ...

@overload
def has_key(arg0: Any, arg1: Any = ...) -> Any: ...
@overload
def has_key(arg0: Any, arg1: int = ...) -> bool: ...
@overload
def has_key(arg0: Any, arg1: str = ...) -> bool: ...
@overload
def has_key(arg0: Any, arg1: str = ...) -> int: ...

def initscr(*args: Any, **kwargs: Any) -> Any: ...

def keyname(*args: Any, **kwargs: Any) -> Any: ...

def start_color(*args: Any, **kwargs: Any) -> Any: ...

def tigetstr(*args: Any, **kwargs: Any) -> Any: ...

COLORS: Any
COLOR_PAIRS: Any
KEY_A1: Any
KEY_A3: Any
KEY_B2: Any
KEY_BACKSPACE: Any
KEY_BEG: Any
KEY_BTAB: Any
KEY_C1: Any
KEY_C3: Any
KEY_CANCEL: Any
KEY_CATAB: Any
KEY_CLEAR: Any
KEY_CLOSE: Any
KEY_COMMAND: Any
KEY_COPY: Any
KEY_CREATE: Any
KEY_CTAB: Any
KEY_DC: Any
KEY_DL: Any
KEY_DOWN: Any
KEY_EIC: Any
KEY_END: Any
KEY_ENTER: Any
KEY_EOL: Any
KEY_EOS: Any
KEY_EXIT: Any
KEY_F0: Any
KEY_F1: Any
KEY_F10: Any
KEY_F11: Any
KEY_F12: Any
KEY_F13: Any
KEY_F14: Any
KEY_F15: Any
KEY_F16: Any
KEY_F17: Any
KEY_F18: Any
KEY_F19: Any
KEY_F2: Any
KEY_F20: Any
KEY_F21: Any
KEY_F22: Any
KEY_F23: Any
KEY_F24: Any
KEY_F25: Any
KEY_F26: Any
KEY_F27: Any
KEY_F28: Any
KEY_F29: Any
KEY_F3: Any
KEY_F30: Any
KEY_F31: Any
KEY_F32: Any
KEY_F33: Any
KEY_F34: Any
KEY_F35: Any
KEY_F36: Any
KEY_F37: Any
KEY_F38: Any
KEY_F39: Any
KEY_F4: Any
KEY_F40: Any
KEY_F41: Any
KEY_F42: Any
KEY_F43: Any
KEY_F44: Any
KEY_F45: Any
KEY_F46: Any
KEY_F47: Any
KEY_F48: Any
KEY_F49: Any
KEY_F5: Any
KEY_F50: Any
KEY_F51: Any
KEY_F52: Any
KEY_F53: Any
KEY_F54: Any
KEY_F55: Any
KEY_F56: Any
KEY_F57: Any
KEY_F58: Any
KEY_F59: Any
KEY_F6: Any
KEY_F60: Any
KEY_F61: Any
KEY_F62: Any
KEY_F63: Any
KEY_F7: Any
KEY_F8: Any
KEY_F9: Any
KEY_FIND: Any
KEY_HELP: Any
KEY_HOME: Any
KEY_IC: Any
KEY_IL: Any
KEY_LEFT: Any
KEY_LL: Any
KEY_MARK: Any
KEY_MESSAGE: Any
KEY_MOVE: Any
KEY_NEXT: Any
KEY_NPAGE: Any
KEY_OPEN: Any
KEY_OPTIONS: Any
KEY_PPAGE: Any
KEY_PREVIOUS: Any
KEY_PRINT: Any
KEY_REDO: Any
KEY_REFERENCE: Any
KEY_REFRESH: Any
KEY_REPLACE: Any
KEY_RESTART: Any
KEY_RESUME: Any
KEY_RIGHT: Any
KEY_SAVE: Any
KEY_SBEG: Any
KEY_SCANCEL: Any
KEY_SCOMMAND: Any
KEY_SCOPY: Any
KEY_SCREATE: Any
KEY_SDC: Any
KEY_SDL: Any
KEY_SELECT: Any
KEY_SEND: Any
KEY_SEOL: Any
KEY_SEXIT: Any
KEY_SF: Any
KEY_SFIND: Any
KEY_SHELP: Any
KEY_SHOME: Any
KEY_SIC: Any
KEY_SLEFT: Any
KEY_SMESSAGE: Any
KEY_SMOVE: Any
KEY_SNEXT: Any
KEY_SOPTIONS: Any
KEY_SPREVIOUS: Any
KEY_SPRINT: Any
KEY_SR: Any
KEY_SREDO: Any
KEY_SREPLACE: Any
KEY_SRIGHT: Any
KEY_SRSUME: Any
KEY_SSAVE: Any
KEY_SSUSPEND: Any
KEY_STAB: Any
KEY_SUNDO: Any
KEY_SUSPEND: Any
KEY_UNDO: Any
KEY_UP: Any
__dict__: Any
