# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def logreader(*args: Any, **kwargs: Any) -> Any: ...

def profiler(*args: Any, **kwargs: Any) -> Any: ...

ProfilerError: Any
WHAT_ADD_INFO: Final[int] = 19
WHAT_DEFINE_FILE: Final[int] = 35
WHAT_DEFINE_FUNC: Final[int] = 67
WHAT_ENTER: Final[int] = 0
WHAT_EXIT: Final[int] = 1
WHAT_LINENO: Final[int] = 2
