# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def FileIO(*args: Any, **kwargs: Any) -> Any: ...

BlockingIOError: Any
BufferedRWPair: Any
BufferedRandom: Any
BufferedReader: Any
BufferedWriter: Any
BytesIO: Any
DEFAULT_BUFFER_SIZE: Any
IncrementalNewlineDecoder: Any
StringIO: Any
TextIOWrapper: Any
UnsupportedOperation: Any
_BufferedIOBase: Any
_IOBase: Any
_RawIOBase: Any
_TextIOBase: Any
open: Any
