# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def SSLError(*args: Any, **kwargs: Any) -> Any: ...

def enum_certificates(*args: Any, **kwargs: Any) -> Any: ...

def get_default_verify_paths(*args: Any, **kwargs: Any) -> Any: ...

def nid2obj(*args: Any, **kwargs: Any) -> Any: ...

def txt2obj(*args: Any, **kwargs: Any) -> Any: ...

CERT_NONE: Any
CERT_OPTIONAL: Final[int] = 1
CERT_REQUIRED: Any
HAS_ALPN: Any
HAS_ECDH: Any
HAS_NPN: Any
HAS_SNI: Any
HAS_TLS_UNIQUE: Any
HAS_TLSv1_3: Any
OPENSSL_VERSION: Any
OPENSSL_VERSION_INFO: Any
OPENSSL_VERSION_NUMBER: Any
RAND_add: Any
RAND_egd: Any
RAND_status: Any
SSLEOFError: Any
SSLSyscallError: Any
SSLWantReadError: Any
SSLWantWriteError: Any
SSLZeroReturnError: Any
SSL_ERROR_EOF: Final[int] = 8
SSL_ERROR_INVALID_ERROR_CODE: Final[int] = 10
SSL_ERROR_SSL: Final[int] = 1
SSL_ERROR_SYSCALL: Final[int] = 5
SSL_ERROR_WANT_CONNECT: Final[int] = 7
SSL_ERROR_WANT_READ: Final[int] = 2
SSL_ERROR_WANT_WRITE: Final[int] = 3
SSL_ERROR_WANT_X509_LOOKUP: Final[int] = 4
SSL_ERROR_ZERO_RETURN: Final[int] = 6
_OPENSSL_API_VERSION: Any
_SSLContext: Any
enum_crls: Any
