# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def symtable(*args: Any, **kwargs: Any) -> Any: ...

CELL: Final[int] = 5
DEF_BOUND: Final[int] = 70
DEF_GLOBAL: Final[int] = 1
DEF_IMPORT: Final[int] = 64
DEF_LOCAL: Final[int] = 2
DEF_PARAM: Final[int] = 4
FREE: Final[int] = 4
GLOBAL_EXPLICIT: Final[int] = 2
GLOBAL_IMPLICIT: Final[int] = 3
LOCAL: Final[int] = 1
OPT_BARE_EXEC: Final[int] = 4
OPT_EXEC: Final[int] = 2
OPT_IMPORT_STAR: Final[int] = 1
SCOPE_MASK: Any
SCOPE_OFF: Final[int] = 11
TYPE_CLASS: Final[int] = 1
TYPE_FUNCTION: Final[int] = 0
TYPE_MODULE: Final[int] = 2
USE: Final[int] = 8
