# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload
import Math

@overload
def append(arg0: Any, arg1: Any = ...) -> None: ...
@overload
def append(arg0: Any, arg1: Any = ...) -> bool: ...
@overload
def append(arg0: Any, arg1: ParticleSystemAction = ...) -> None: ...
@overload
def append(arg0: Any, arg1: Any = ..., arg2: Any = ...) -> bool: ...

def flat(*args: Any, **kwargs: Any) -> Any: ...

@overload
def type(arg0: Any = ...) -> GameObject: ...
@overload
def type(arg0: Any = ...) -> int: ...
@overload
def type(arg0: Any = ...) -> str: ...

INT_MAX: Any
SIZEOF_PYGC_HEAD: Any
UINT_MAX: Any
__module__: Any
base: Any
item: Any
leng: Any
vari: Any
