# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def TclError(*args: Any, **kwargs: Any) -> Any: ...

def create(arg0: Any, arg1: str, arg2: str, arg3: str, arg4: str, arg5: int, arg6: int, arg7: int, arg8: int = ..., arg9: int = ...) -> bool: ...

EXCEPTION: Any
READABLE: Any
TCL_VERSION: Any
TK_VERSION: Any
Tcl_Obj: Any
WRITABLE: Any
_cnfmerge: Any
_flatten: Any
createfilehandler: Any
deletefilehandler: Any
