# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def warn(*args: Any, **kwargs: Any) -> Any: ...

def warn_explicit(*args: Any, **kwargs: Any) -> Any: ...

default_action: Any
filters: Any
once_registry: Any
