# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def _remove_dead_weakref(*args: Any, **kwargs: Any) -> Any: ...

def proxy(*args: Any, **kwargs: Any) -> Any: ...

@overload
def ref(arg0: Any) -> Any: ...
@overload
def ref(arg0: Any) -> None: ...
@overload
def ref(arg0: Any, arg1: Any = ...) -> None: ...

CallableProxyType: Any
ProxyType: Any
ReferenceType: Any
getweakrefcount: Any
getweakrefs: Any
