# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def EnumKey(*args: Any, **kwargs: Any) -> Any: ...

def OpenKey(*args: Any, **kwargs: Any) -> Any: ...

def QueryValueEx(*args: Any, **kwargs: Any) -> Any: ...

CloseKey: Any
EnumValue: Any
HKEY_CLASSES_ROOT: Final[int] = -2147483648
HKEY_CURRENT_USER: Any
HKEY_LOCAL_MACHINE: Any
HKEY_USERS: Final[int] = -2147483645
OpenKeyEx: Any
REG_SZ: Final[int] = 1
error: Any
