# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class WithinTurretLimitsResult:
    AboveUpperLimit: ClassVar[WithinTurretLimitsResult]  # native value: 1
    BelowLowerLimit: ClassVar[WithinTurretLimitsResult]  # native value: 2
    WithinLimits: ClassVar[WithinTurretLimitsResult]  # native value: 0

AboveUpperLimit: Final[WithinTurretLimitsResult] = WithinTurretLimitsResult.AboveUpperLimit
BelowLowerLimit: Final[WithinTurretLimitsResult] = WithinTurretLimitsResult.BelowLowerLimit
WithinLimits: Final[WithinTurretLimitsResult] = WithinTurretLimitsResult.WithinLimits
