# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class TargetDetectionType:
    Direct: ClassVar[TargetDetectionType]  # native value: 0
    Indirect: ClassVar[TargetDetectionType]  # native value: 2
    NotDetected: ClassVar[TargetDetectionType]  # native value: 255
    Undetected: ClassVar[TargetDetectionType]  # native value: 1

Direct: Final[TargetDetectionType] = TargetDetectionType.Direct
Indirect: Final[TargetDetectionType] = TargetDetectionType.Indirect
NotDetected: Final[TargetDetectionType] = TargetDetectionType.NotDetected
Undetected: Final[TargetDetectionType] = TargetDetectionType.Undetected
