# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class ModifierType:
    Add: ClassVar[ModifierType]  # native value: 1
    Multiply: ClassVar[ModifierType]  # native value: 2
    Override: ClassVar[ModifierType]  # native value: 4
    Set: ClassVar[ModifierType]  # native value: 0
    SumMultiply: ClassVar[ModifierType]  # native value: 3

Add: Final[ModifierType] = ModifierType.Add
Multiply: Final[ModifierType] = ModifierType.Multiply
Override: Final[ModifierType] = ModifierType.Override
Set: Final[ModifierType] = ModifierType.Set
SumMultiply: Final[ModifierType] = ModifierType.SumMultiply
