# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

HealthRestoreAbilityComponent: Any
HealthRestoreAbilityMappingEntry: Any
HealthRestoreAbilitySystem: Any
