# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

BeamRibbonComponent: Any

class BeamRibbonAvoidanceType:
    Terrain: ClassVar[BeamRibbonAvoidanceType]  # native value: 1
    TerrainAndStaticObstacles: ClassVar[BeamRibbonAvoidanceType]  # native value: 2

Terrain: Final[BeamRibbonAvoidanceType] = BeamRibbonAvoidanceType.Terrain
TerrainAndStaticObstacles: Final[BeamRibbonAvoidanceType] = BeamRibbonAvoidanceType.TerrainAndStaticObstacles
