# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload
import Math

def wg_injectNonVolatileUpdate(arg0: int, arg1: int, arg2: Math.Vector3, arg3: Math.Vector3) -> None: ...

def wg_withholdEntity(arg0: int, arg1: bool) -> None: ...
