# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class EaseType:
    CUBIC_IN: ClassVar[EaseType]  # native value: 4
    CUBIC_INOUT: ClassVar[EaseType]  # native value: 6
    CUBIC_OUT: ClassVar[EaseType]  # native value: 5
    EXPO_IN: ClassVar[EaseType]  # native value: 10
    EXPO_INOUT: ClassVar[EaseType]  # native value: 12
    EXPO_OUT: ClassVar[EaseType]  # native value: 11
    LINEAR: ClassVar[EaseType]  # native value: 0
    QUINT_IN: ClassVar[EaseType]  # native value: 7
    QUINT_INOUT: ClassVar[EaseType]  # native value: 9
    QUINT_OUT: ClassVar[EaseType]  # native value: 8
    SQUARE_IN: ClassVar[EaseType]  # native value: 1
    SQUARE_INOUT: ClassVar[EaseType]  # native value: 3
    SQUARE_OUT: ClassVar[EaseType]  # native value: 2

CUBIC_IN: Final[EaseType] = EaseType.CUBIC_IN
CUBIC_INOUT: Final[EaseType] = EaseType.CUBIC_INOUT
CUBIC_OUT: Final[EaseType] = EaseType.CUBIC_OUT
EXPO_IN: Final[EaseType] = EaseType.EXPO_IN
EXPO_INOUT: Final[EaseType] = EaseType.EXPO_INOUT
EXPO_OUT: Final[EaseType] = EaseType.EXPO_OUT
LINEAR: Final[EaseType] = EaseType.LINEAR
QUINT_IN: Final[EaseType] = EaseType.QUINT_IN
QUINT_INOUT: Final[EaseType] = EaseType.QUINT_INOUT
QUINT_OUT: Final[EaseType] = EaseType.QUINT_OUT
SQUARE_IN: Final[EaseType] = EaseType.SQUARE_IN
SQUARE_INOUT: Final[EaseType] = EaseType.SQUARE_INOUT
SQUARE_OUT: Final[EaseType] = EaseType.SQUARE_OUT
