# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

CameraComponent: Any
CameraFlightComponent: Any
DofComponent: Any
FovComponent: Any
IdleComponent: Any
OrbitComponent: Any
ParallaxComponent: Any
ShiftComponent: Any
