# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

ArmorHitPlacement: Any
VariableStorageComponent: Any
VariableType: Any
game_events: Any
