# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def sequenceSubscribe(arg0: int, arg1: str, arg2: Any) -> None: ...

ArmorHitPlacement: Any
VariableStorageComponent: Any
VariableType: Any
game_events: Any
