# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def ReplicationState(arg0: Any, arg1: int) -> None: ...

def getGameObjectByNetworkID(arg0: int, arg1: int) -> GameObject: ...

def processCreateDynamicComponent(arg0: ObjectNetworkId, arg1: int, arg2: Any) -> None: ...

def processDestroyDynamicComponent(arg0: ObjectNetworkId, arg1: int, arg2: Any) -> None: ...

C_INVALID_NETWORK_OBJECT_ID: Any
ClientReplicableDataSingleton: Any

class ObjectCommand:
    Add: ClassVar[ObjectCommand]  # native value: 0
    Remove: ClassVar[ObjectCommand]  # native value: 1
    Update: ClassVar[ObjectCommand]  # native value: 2

Add: Final[ObjectCommand] = ObjectCommand.Add
Remove: Final[ObjectCommand] = ObjectCommand.Remove
Update: Final[ObjectCommand] = ObjectCommand.Update
