# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def onClientCompositionAboutToBeRemoved(arg0: GameObject) -> None: ...

Compound: Any
CompoundBasedComposerComponent: Any
LocalTransformNodeFollower: Any
NodeLeaderComponent: Any

class NodeInteractType:
    DRIVE: ClassVar[NodeInteractType]  # native value: 2
    FOLLOW: ClassVar[NodeInteractType]  # native value: 1
    NONE: ClassVar[NodeInteractType]  # native value: 0

DRIVE: Final[NodeInteractType] = NodeInteractType.DRIVE
FOLLOW: Final[NodeInteractType] = NodeInteractType.FOLLOW
NONE: Final[NodeInteractType] = NodeInteractType.NONE
