# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def AppearanceDeactivatedEvent(arg0: Any, arg1: GameObject) -> None: ...

def AppearanceRefreshRequestedEvent(arg0: Any, arg1: GameObject = ..., arg2: Any = ..., arg3: Any = ..., arg4: dict[str, str] = ..., arg5: list[Any] = ..., arg6: list[Any] = ..., arg7: list[tuple[str, list[Any]]] = ...) -> None: ...

def onClientCompositionAboutToBeRemoved(arg0: GameObject) -> None: ...

Compound: Any
CompoundBasedComposerComponent: Any
LocalTransformNodeFollower: Any
NodeLeaderComponent: Any

class NodeInteractType:
    DRIVE: ClassVar[NodeInteractType]  # native value: 2
    FOLLOW: ClassVar[NodeInteractType]  # native value: 1
    NONE: ClassVar[NodeInteractType]  # native value: 0

DRIVE: Final[NodeInteractType] = NodeInteractType.DRIVE
FOLLOW: Final[NodeInteractType] = NodeInteractType.FOLLOW
NONE: Final[NodeInteractType] = NodeInteractType.NONE
