# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class CoverMode:
    Blind: ClassVar[CoverMode]  # native value: 2
    Defensive: ClassVar[CoverMode]  # native value: 1
    Normal: ClassVar[CoverMode]  # native value: 0

Blind: Final[CoverMode] = CoverMode.Blind
Defensive: Final[CoverMode] = CoverMode.Defensive
Normal: Final[CoverMode] = CoverMode.Normal
