# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class CoverAggressiveMode:
    AggressiveFirst: ClassVar[CoverAggressiveMode]  # native value: 2
    AggressiveOnly: ClassVar[CoverAggressiveMode]  # native value: 1
    Default: ClassVar[CoverAggressiveMode]  # native value: 0

class IsCoverValidResult:
    CoverInvalid: ClassVar[IsCoverValidResult]  # native value: 2
    CoverValid: ClassVar[IsCoverValidResult]  # native value: 1
    NoCover: ClassVar[IsCoverValidResult]  # native value: 0

class ReconCoverMode:
    Aggressive: ClassVar[ReconCoverMode]  # native value: 2
    Defensive: ClassVar[ReconCoverMode]  # native value: 1
    Normal: ClassVar[ReconCoverMode]  # native value: 0

Aggressive: Final[ReconCoverMode] = ReconCoverMode.Aggressive
AggressiveFirst: Final[CoverAggressiveMode] = CoverAggressiveMode.AggressiveFirst
AggressiveOnly: Final[CoverAggressiveMode] = CoverAggressiveMode.AggressiveOnly
CoverInvalid: Final[IsCoverValidResult] = IsCoverValidResult.CoverInvalid
CoverValid: Final[IsCoverValidResult] = IsCoverValidResult.CoverValid
Default: Final[CoverAggressiveMode] = CoverAggressiveMode.Default
Defensive: Final[ReconCoverMode] = ReconCoverMode.Defensive
NoCover: Final[IsCoverValidResult] = IsCoverValidResult.NoCover
Normal: Final[ReconCoverMode] = ReconCoverMode.Normal
