# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class OACommandType:
    CMD_AUTO_DETECT: ClassVar[OACommandType]  # native value: 10001
    CMD_EXIT: ClassVar[OACommandType]  # native value: 0
    CMD_GET_ALL_OPTIONS: ClassVar[OACommandType]  # native value: 2
    CMD_GET_BENCHMARKS: ClassVar[OACommandType]  # native value: 5
    CMD_GET_CURRENT_OPTIONS: ClassVar[OACommandType]  # native value: 3
    CMD_RESTART: ClassVar[OACommandType]  # native value: 10000
    CMD_RUN: ClassVar[OACommandType]  # native value: 1
    CMD_RUN_BENCHMARK: ClassVar[OACommandType]  # native value: 6
    CMD_SET_OPTIONS: ClassVar[OACommandType]  # native value: 4

CMD_AUTO_DETECT: Final[OACommandType] = OACommandType.CMD_AUTO_DETECT
CMD_EXIT: Final[OACommandType] = OACommandType.CMD_EXIT
CMD_GET_ALL_OPTIONS: Final[OACommandType] = OACommandType.CMD_GET_ALL_OPTIONS
CMD_GET_BENCHMARKS: Final[OACommandType] = OACommandType.CMD_GET_BENCHMARKS
CMD_GET_CURRENT_OPTIONS: Final[OACommandType] = OACommandType.CMD_GET_CURRENT_OPTIONS
CMD_RESTART: Final[OACommandType] = OACommandType.CMD_RESTART
CMD_RUN: Final[OACommandType] = OACommandType.CMD_RUN
CMD_RUN_BENCHMARK: Final[OACommandType] = OACommandType.CMD_RUN_BENCHMARK
CMD_SET_OPTIONS: Final[OACommandType] = OACommandType.CMD_SET_OPTIONS
