# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class KillResolveType:
    FREEZE: ClassVar[KillResolveType]  # native value: 1
    NONE: ClassVar[KillResolveType]  # native value: 0
    PUSH: ClassVar[KillResolveType]  # native value: 2

FREEZE: Final[KillResolveType] = KillResolveType.FREEZE
NONE: Final[KillResolveType] = KillResolveType.NONE
PUSH: Final[KillResolveType] = KillResolveType.PUSH
