# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class DamageType:
    ABSOLUTE_VALUE: ClassVar[DamageType]  # native value: 0
    PERCENTS: ClassVar[DamageType]  # native value: 1

ABSOLUTE_VALUE: Final[DamageType] = DamageType.ABSOLUTE_VALUE
PERCENTS: Final[DamageType] = DamageType.PERCENTS
