# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def DebugDrawer(arg0: Any = ..., arg1: int = ...) -> Any: ...

class BlendMode:
    BM_ADDITIVE: ClassVar[BlendMode]  # native value: 2
    BM_ADDITIVE_NO_SCALING: ClassVar[BlendMode]  # native value: 3
    BM_OPAQUE: ClassVar[BlendMode]  # native value: 0
    BM_STANDARD: ClassVar[BlendMode]  # native value: 1
    BM_SUBTRACTIVE: ClassVar[BlendMode]  # native value: 4
    BM_SUBTRACTIVE_REVERSED_NO_SCALING: ClassVar[BlendMode]  # native value: 5
    BM_TRANSPARENT: ClassVar[BlendMode]  # native value: 6

BM_ADDITIVE: Final[BlendMode] = BlendMode.BM_ADDITIVE
BM_ADDITIVE_NO_SCALING: Final[BlendMode] = BlendMode.BM_ADDITIVE_NO_SCALING
BM_OPAQUE: Final[BlendMode] = BlendMode.BM_OPAQUE
BM_STANDARD: Final[BlendMode] = BlendMode.BM_STANDARD
BM_SUBTRACTIVE: Final[BlendMode] = BlendMode.BM_SUBTRACTIVE
BM_SUBTRACTIVE_REVERSED_NO_SCALING: Final[BlendMode] = BlendMode.BM_SUBTRACTIVE_REVERSED_NO_SCALING
BM_TRANSPARENT: Final[BlendMode] = BlendMode.BM_TRANSPARENT
