# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload
import Math

def fini(*args: Any, **kwargs: Any) -> Any: ...

def init() -> bool: ...

dev_input_handler: Any
g_change_manager: Any
g_devInputHandlerInstance: Any
replay_override: Any
