# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def Parser(*args: Any, **kwargs: Any) -> Any: ...

Reporter: Any
frontend: Any
nodes: Any
