# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload
import Math

@overload
def local(arg0: Any = ...) -> Any: ...
@overload
def local(arg0: Any = ...) -> Math.Matrix: ...
@overload
def local(arg0: Any = ...) -> bool: ...
@overload
def local(arg0: Any = ...) -> float: ...
@overload
def local(arg0: Any = ...) -> list[Any]: ...
@overload
def local(arg0: Any = ...) -> str: ...

monkey: Any
pywsgi: Any
wsgi: Any
