# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

GpuDecalsReceiverComponent: Any
GpuDecalsReceiverComponentSystem: Any
INVALID_BLOCK_IDX: Any
