# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

FireComponent: Any
OverheatComponent: Any
StunComponent: Any
UnderWaterComponent: Any
