# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload
import Math

def InputTriggerPressed(*args: Any, **kwargs: Any) -> Any: ...

def KeyInputAction(*args: Any, **kwargs: Any) -> Any: ...

def inputSystem() -> Any: ...

@overload
def isActive(arg0: Any) -> bool: ...
@overload
def isActive(arg0: Any, arg1: GameObject = ...) -> bool: ...
@overload
def isActive(arg0: Any, arg1: str = ...) -> bool: ...
@overload
def isActive(arg0: Any, arg1: str = ..., arg2: Any = ...) -> bool: ...

@overload
def isFired(arg0: int) -> bool: ...
@overload
def isFired(arg0: int, arg1: int) -> bool: ...

def loadProfiles(arg0: str | None = ...) -> bool: ...

def setCommandMapping(arg0: Any) -> None: ...

def setCommandMappingNames(arg0: dict[int, str]) -> None: ...

def unloadProfiles() -> None: ...

InputLayer: Any

class TriggerEvent:
    Canceled: ClassVar[TriggerEvent]  # native value: 8
    Completed: ClassVar[TriggerEvent]  # native value: 16
    OnProcess: ClassVar[TriggerEvent]  # native value: 4
    Started: ClassVar[TriggerEvent]  # native value: 2
    Triggered: ClassVar[TriggerEvent]  # native value: 1

Canceled: Final[TriggerEvent] = TriggerEvent.Canceled
Completed: Final[TriggerEvent] = TriggerEvent.Completed
OnProcess: Final[TriggerEvent] = TriggerEvent.OnProcess
Started: Final[TriggerEvent] = TriggerEvent.Started
Triggered: Final[TriggerEvent] = TriggerEvent.Triggered
