# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def InputAction(arg0: Any, arg1: float) -> None: ...

def InputTriggerHold(arg0: Any, arg1: float = ...) -> None: ...

def InputTriggerPressed(*args: Any, **kwargs: Any) -> Any: ...

def InputTriggerTap(arg0: Any, arg1: float = ...) -> None: ...

InputSingleton: Any

class TriggerEvent:
    Canceled: ClassVar[TriggerEvent]  # native value: 8
    Completed: ClassVar[TriggerEvent]  # native value: 16
    OnProcess: ClassVar[TriggerEvent]  # native value: 4
    Started: ClassVar[TriggerEvent]  # native value: 2
    Triggered: ClassVar[TriggerEvent]  # native value: 1

Canceled: Final[TriggerEvent] = TriggerEvent.Canceled
Completed: Final[TriggerEvent] = TriggerEvent.Completed
OnProcess: Final[TriggerEvent] = TriggerEvent.OnProcess
Started: Final[TriggerEvent] = TriggerEvent.Started
Triggered: Final[TriggerEvent] = TriggerEvent.Triggered
