# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

Exception: Any
System: Any
lang: Any
os: Any
vendor: Any
version: Any
vm: Any
