# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def MailList(*args: Any, **kwargs: Any) -> Any: ...

def Message(*args: Any, **kwargs: Any) -> Any: ...

Utils: Any
