# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class EmissionType:
    COLOR: ClassVar[EmissionType]  # native value: 0
    TEMPERATURE: ClassVar[EmissionType]  # native value: 1

class InfluenceMask:
    ALL: ClassVar[InfluenceMask]  # native value: 31
    DYNAMIC: ClassVar[InfluenceMask]  # native value: 16
    FLORA: ClassVar[InfluenceMask]  # native value: 2
    NONE: ClassVar[InfluenceMask]  # native value: 0
    STATIC: ClassVar[InfluenceMask]  # native value: 8
    TERRAIN: ClassVar[InfluenceMask]  # native value: 1
    TREE: ClassVar[InfluenceMask]  # native value: 4

class ProjectionType:
    CYLINDRICAL: ClassVar[ProjectionType]  # native value: 1
    ORTHONORMAL: ClassVar[ProjectionType]  # native value: 0

ALL: Final[InfluenceMask] = InfluenceMask.ALL
COLOR: Final[EmissionType] = EmissionType.COLOR
CYLINDRICAL: Final[ProjectionType] = ProjectionType.CYLINDRICAL
DYNAMIC: Final[InfluenceMask] = InfluenceMask.DYNAMIC
FLORA: Final[InfluenceMask] = InfluenceMask.FLORA
NONE: Final[InfluenceMask] = InfluenceMask.NONE
ORTHONORMAL: Final[ProjectionType] = ProjectionType.ORTHONORMAL
STATIC: Final[InfluenceMask] = InfluenceMask.STATIC
TEMPERATURE: Final[EmissionType] = EmissionType.TEMPERATURE
TERRAIN: Final[InfluenceMask] = InfluenceMask.TERRAIN
TREE: Final[InfluenceMask] = InfluenceMask.TREE
