# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def mmap(*args: Any, **kwargs: Any) -> Any: ...

ACCESS_READ: Final[int] = 1
PAGESIZE: Any
