# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def FloatLatencyDelayingFilter(*args: Any, **kwargs: Any) -> Any: ...

FloatFilterRetriever: Any
