# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def attrgetter(*args: Any, **kwargs: Any) -> Any: ...

def contains(arg0: Any, arg1: Any) -> bool: ...

def isMappingType(*args: Any, **kwargs: Any) -> Any: ...

def itemgetter(*args: Any, **kwargs: Any) -> Any: ...

def methodcaller(*args: Any, **kwargs: Any) -> Any: ...

def setitem(*args: Any, **kwargs: Any) -> Any: ...

def sub(arg0: Any, arg1: str) -> Any: ...

def truth(*args: Any, **kwargs: Any) -> Any: ...

_compare_digest: Any
add: Any
and_: Any
delitem: Any
div: Any
eq: Any
ge: Any
getitem: Any
getslice: Any
gt: Any
iand: Any
ior: Any
le: Any
lt: Any
mul: Any
ne: Any
or_: Any
setslice: Any
truediv: Any
xor: Any
