# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload
import Math

def MeshColliderDesc(arg0: Any, arg1: Math.Matrix) -> None: ...

CameraCollideComponent: Any
CollidersComponent: Any
DynamicCollisionLinker: Any
PhysicalDebrisSpawnerComponent: Any
