# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def PrefabDataListLoader(arg0: Any) -> Any: ...

def PrefabDataLoader(arg0: Any) -> bool: ...

PrefabData: Any
