# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class UniqueFor:
    Parent: ClassVar[UniqueFor]  # native value: 1
    Root: ClassVar[UniqueFor]  # native value: 0

Parent: Final[UniqueFor] = UniqueFor.Parent
Root: Final[UniqueFor] = UniqueFor.Root
