# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

GunReloadedComponent: Any
ProjectileHitsReceivedComponent: Any
ShotsDoneComponent: Any
