# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class PyResourceType:
    ANIMATION: ClassVar[PyResourceType]  # native value: 8
    AREA: ClassVar[PyResourceType]  # native value: 2
    DYNAMIC_ID: ClassVar[PyResourceType]  # native value: 10
    ENTRY: ClassVar[PyResourceType]  # native value: 1
    IMAGE: ClassVar[PyResourceType]  # native value: 5
    LAYOUT: ClassVar[PyResourceType]  # native value: 3
    SOUND: ClassVar[PyResourceType]  # native value: 6
    STRING: ClassVar[PyResourceType]  # native value: 4
    STYLE: ClassVar[PyResourceType]  # native value: 7
    SUBTITLES: ClassVar[PyResourceType]  # native value: 11
    UNDEFINED: ClassVar[PyResourceType]  # native value: 0
    VIDEO: ClassVar[PyResourceType]  # native value: 9

ANIMATION: Final[PyResourceType] = PyResourceType.ANIMATION
AREA: Final[PyResourceType] = PyResourceType.AREA
DYNAMIC_ID: Final[PyResourceType] = PyResourceType.DYNAMIC_ID
ENTRY: Final[PyResourceType] = PyResourceType.ENTRY
IMAGE: Final[PyResourceType] = PyResourceType.IMAGE
LAYOUT: Final[PyResourceType] = PyResourceType.LAYOUT
SOUND: Final[PyResourceType] = PyResourceType.SOUND
STRING: Final[PyResourceType] = PyResourceType.STRING
STYLE: Final[PyResourceType] = PyResourceType.STYLE
SUBTITLES: Final[PyResourceType] = PyResourceType.SUBTITLES
UNDEFINED: Final[PyResourceType] = PyResourceType.UNDEFINED
VIDEO: Final[PyResourceType] = PyResourceType.VIDEO
