# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class ResourceFormat:
    A16B16G16R16: ClassVar[ResourceFormat]  # native value: 12
    A16B16G16R16F: ClassVar[ResourceFormat]  # native value: 36
    A1R5G5B5: ClassVar[ResourceFormat]  # native value: 6
    A2B10G10R10: ClassVar[ResourceFormat]  # native value: 8
    A32B32G32R32F: ClassVar[ResourceFormat]  # native value: 39
    A8: ClassVar[ResourceFormat]  # native value: 7
    A8B8G8R8: ClassVar[ResourceFormat]  # native value: 9
    A8L8: ClassVar[ResourceFormat]  # native value: 15
    A8R8G8B8: ClassVar[ResourceFormat]  # native value: 2
    D15S1: ClassVar[ResourceFormat]  # native value: 26
    D16: ClassVar[ResourceFormat]  # native value: 30
    D16_LOCKABLE: ClassVar[ResourceFormat]  # native value: 24
    D24S8: ClassVar[ResourceFormat]  # native value: 27
    D24X4S4: ClassVar[ResourceFormat]  # native value: 29
    D24X8: ClassVar[ResourceFormat]  # native value: 28
    D32: ClassVar[ResourceFormat]  # native value: 25
    D32F_LOCKABLE: ClassVar[ResourceFormat]  # native value: 32
    DXT1: ClassVar[ResourceFormat]  # native value: 17
    DXT2: ClassVar[ResourceFormat]  # native value: 18
    DXT3: ClassVar[ResourceFormat]  # native value: 19
    DXT4: ClassVar[ResourceFormat]  # native value: 20
    DXT5: ClassVar[ResourceFormat]  # native value: 21
    G16R16: ClassVar[ResourceFormat]  # native value: 11
    G16R16F: ClassVar[ResourceFormat]  # native value: 35
    G32R32F: ClassVar[ResourceFormat]  # native value: 38
    L16: ClassVar[ResourceFormat]  # native value: 31
    L8: ClassVar[ResourceFormat]  # native value: 16
    R16F: ClassVar[ResourceFormat]  # native value: 34
    R32F: ClassVar[ResourceFormat]  # native value: 37
    R5G6B5: ClassVar[ResourceFormat]  # native value: 4
    R8G8B8: ClassVar[ResourceFormat]  # native value: 1
    UNKNOWN: ClassVar[ResourceFormat]  # native value: 0
    X1R5G5B5: ClassVar[ResourceFormat]  # native value: 5
    X8B8G8R8: ClassVar[ResourceFormat]  # native value: 10
    X8R8G8B8: ClassVar[ResourceFormat]  # native value: 3

A16B16G16R16: Final[ResourceFormat] = ResourceFormat.A16B16G16R16
A16B16G16R16F: Final[ResourceFormat] = ResourceFormat.A16B16G16R16F
A1R5G5B5: Final[ResourceFormat] = ResourceFormat.A1R5G5B5
A2B10G10R10: Final[ResourceFormat] = ResourceFormat.A2B10G10R10
A32B32G32R32F: Final[ResourceFormat] = ResourceFormat.A32B32G32R32F
A8: Final[ResourceFormat] = ResourceFormat.A8
A8B8G8R8: Final[ResourceFormat] = ResourceFormat.A8B8G8R8
A8L8: Final[ResourceFormat] = ResourceFormat.A8L8
A8R8G8B8: Final[ResourceFormat] = ResourceFormat.A8R8G8B8
D15S1: Final[ResourceFormat] = ResourceFormat.D15S1
D16: Final[ResourceFormat] = ResourceFormat.D16
D16_LOCKABLE: Final[ResourceFormat] = ResourceFormat.D16_LOCKABLE
D24S8: Final[ResourceFormat] = ResourceFormat.D24S8
D24X4S4: Final[ResourceFormat] = ResourceFormat.D24X4S4
D24X8: Final[ResourceFormat] = ResourceFormat.D24X8
D32: Final[ResourceFormat] = ResourceFormat.D32
D32F_LOCKABLE: Final[ResourceFormat] = ResourceFormat.D32F_LOCKABLE
DXT1: Final[ResourceFormat] = ResourceFormat.DXT1
DXT2: Final[ResourceFormat] = ResourceFormat.DXT2
DXT3: Final[ResourceFormat] = ResourceFormat.DXT3
DXT4: Final[ResourceFormat] = ResourceFormat.DXT4
DXT5: Final[ResourceFormat] = ResourceFormat.DXT5
G16R16: Final[ResourceFormat] = ResourceFormat.G16R16
G16R16F: Final[ResourceFormat] = ResourceFormat.G16R16F
G32R32F: Final[ResourceFormat] = ResourceFormat.G32R32F
L16: Final[ResourceFormat] = ResourceFormat.L16
L8: Final[ResourceFormat] = ResourceFormat.L8
R16F: Final[ResourceFormat] = ResourceFormat.R16F
R32F: Final[ResourceFormat] = ResourceFormat.R32F
R5G6B5: Final[ResourceFormat] = ResourceFormat.R5G6B5
R8G8B8: Final[ResourceFormat] = ResourceFormat.R8G8B8
UNKNOWN: Final[ResourceFormat] = ResourceFormat.UNKNOWN
X1R5G5B5: Final[ResourceFormat] = ResourceFormat.X1R5G5B5
X8B8G8R8: Final[ResourceFormat] = ResourceFormat.X8B8G8R8
X8R8G8B8: Final[ResourceFormat] = ResourceFormat.X8R8G8B8
