# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class HiddenPositionTarget:
    CoverPoint: ClassVar[HiddenPositionTarget]  # native value: 1
    Self: ClassVar[HiddenPositionTarget]  # native value: 0
    ShootingPoint: ClassVar[HiddenPositionTarget]  # native value: 2

class HiddenPositionTargetState:
    Move: ClassVar[HiddenPositionTargetState]  # native value: 1
    Stay: ClassVar[HiddenPositionTargetState]  # native value: 0

class TimeOffset:
    ReloadTimeLeft: ClassVar[TimeOffset]  # native value: 1
    Zero: ClassVar[TimeOffset]  # native value: 0

class VehicleConstantAttribute:
    BotSkill: ClassVar[VehicleConstantAttribute]  # native value: 2
    GunHorizontalAngleLimit: ClassVar[VehicleConstantAttribute]  # native value: 0
    GunMinusChassisRotationSpeed: ClassVar[VehicleConstantAttribute]  # native value: 1

class VehicleEnum:
    CirclingTarget: ClassVar[VehicleEnum]  # native value: 2
    CurrentTarget: ClassVar[VehicleEnum]  # native value: 1
    Self: ClassVar[VehicleEnum]  # native value: 0

class ZoneType:
    MoveFrom: ClassVar[ZoneType]  # native value: 0
    ShootAt: ClassVar[ZoneType]  # native value: 1

BotSkill: Final[VehicleConstantAttribute] = VehicleConstantAttribute.BotSkill
CirclingTarget: Final[VehicleEnum] = VehicleEnum.CirclingTarget
CoverPoint: Final[HiddenPositionTarget] = HiddenPositionTarget.CoverPoint
CurrentTarget: Final[VehicleEnum] = VehicleEnum.CurrentTarget
GunHorizontalAngleLimit: Final[VehicleConstantAttribute] = VehicleConstantAttribute.GunHorizontalAngleLimit
GunMinusChassisRotationSpeed: Final[VehicleConstantAttribute] = VehicleConstantAttribute.GunMinusChassisRotationSpeed
Move: Final[HiddenPositionTargetState] = HiddenPositionTargetState.Move
MoveFrom: Final[ZoneType] = ZoneType.MoveFrom
ReloadTimeLeft: Final[TimeOffset] = TimeOffset.ReloadTimeLeft
Self: Final[HiddenPositionTarget] = HiddenPositionTarget.Self
ShootAt: Final[ZoneType] = ZoneType.ShootAt
ShootingPoint: Final[HiddenPositionTarget] = HiddenPositionTarget.ShootingPoint
Stay: Final[HiddenPositionTargetState] = HiddenPositionTargetState.Stay
Zero: Final[TimeOffset] = TimeOffset.Zero
