# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class RecreateMethod:
    FromScratch: ClassVar[RecreateMethod]  # native value: 0
    PrefabChild: ClassVar[RecreateMethod]  # native value: 2
    PrefabRoot: ClassVar[RecreateMethod]  # native value: 1

FromScratch: Final[RecreateMethod] = RecreateMethod.FromScratch
PrefabChild: Final[RecreateMethod] = RecreateMethod.PrefabChild
PrefabRoot: Final[RecreateMethod] = RecreateMethod.PrefabRoot
