# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class ValueType:
    ARRAY: ClassVar[ValueType]  # native value: 7
    BOOL: ClassVar[ValueType]  # native value: 3
    MAP: ClassVar[ValueType]  # native value: 8
    NONE: ClassVar[ValueType]  # native value: 0
    NUMBER: ClassVar[ValueType]  # native value: 1
    REAL: ClassVar[ValueType]  # native value: 2
    RESOURCE: ClassVar[ValueType]  # native value: 6
    STRING: ClassVar[ValueType]  # native value: 4
    VIEW_MODEL: ClassVar[ValueType]  # native value: 5

ARRAY: Final[ValueType] = ValueType.ARRAY
BOOL: Final[ValueType] = ValueType.BOOL
MAP: Final[ValueType] = ValueType.MAP
NONE: Final[ValueType] = ValueType.NONE
NUMBER: Final[ValueType] = ValueType.NUMBER
REAL: Final[ValueType] = ValueType.REAL
RESOURCE: Final[ValueType] = ValueType.RESOURCE
STRING: Final[ValueType] = ValueType.STRING
VIEW_MODEL: Final[ValueType] = ValueType.VIEW_MODEL
