# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def exists(arg0: Any) -> bool: ...

def join(*args: Any, **kwargs: Any) -> Any: ...

def split(*args: Any, **kwargs: Any) -> Any: ...

isdir: Any
islink: Any
