# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class SequenceKeyType:
    CubicBezier: ClassVar[SequenceKeyType]  # native value: 3
    Hermite: ClassVar[SequenceKeyType]  # native value: 2
    Linear: ClassVar[SequenceKeyType]  # native value: 1
    List: ClassVar[SequenceKeyType]  # native value: 0
    Quaternion: ClassVar[SequenceKeyType]  # native value: 4
    SpecialRotation: ClassVar[SequenceKeyType]  # native value: 5

CubicBezier: Final[SequenceKeyType] = SequenceKeyType.CubicBezier
Hermite: Final[SequenceKeyType] = SequenceKeyType.Hermite
Linear: Final[SequenceKeyType] = SequenceKeyType.Linear
List: Final[SequenceKeyType] = SequenceKeyType.List
Quaternion: Final[SequenceKeyType] = SequenceKeyType.Quaternion
SpecialRotation: Final[SequenceKeyType] = SequenceKeyType.SpecialRotation
