# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class TrajectoryMode:
    FLAT_AIMING: ClassVar[TrajectoryMode]  # native value: 0
    MIXED_AIMING: ClassVar[TrajectoryMode]  # native value: 2
    STEEP_AIMING: ClassVar[TrajectoryMode]  # native value: 1

FLAT_AIMING: Final[TrajectoryMode] = TrajectoryMode.FLAT_AIMING
MIXED_AIMING: Final[TrajectoryMode] = TrajectoryMode.MIXED_AIMING
STEEP_AIMING: Final[TrajectoryMode] = TrajectoryMode.STEEP_AIMING
