# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def getsignal(*args: Any, **kwargs: Any) -> Any: ...

def signal(arg0: Any, arg1: Any) -> None: ...

CTRL_BREAK_EVENT: Any
CTRL_C_EVENT: Any
SIGINT: Any
SIGKILL: Any
SIGTERM: Any
SIG_DFL: Any
SIG_IGN: Any
__dict__: Any
default_int_handler: Any
