# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def getRecommendedPreset() -> str: ...

def getSpatialAudioPreset() -> str: ...

def reloadSoundEngine() -> None: ...

@overload
def setSpatialAudioEnabled() -> None: ...
@overload
def setSpatialAudioEnabled(arg0: bool) -> None: ...

@overload
def setSpatialAudioPreset() -> None: ...
@overload
def setSpatialAudioPreset(arg0: str) -> None: ...

Audition2D: Any
RTPCComponent: Any

class RTPCSourceType:
    DISTANCE_TO_CANNON: ClassVar[RTPCSourceType]  # native value: 4
    REMAINING_AMMO_CLIP_PERCENT: ClassVar[RTPCSourceType]  # native value: 3
    VALUE: ClassVar[RTPCSourceType]  # native value: 0

DISTANCE_TO_CANNON: Final[RTPCSourceType] = RTPCSourceType.DISTANCE_TO_CANNON
REMAINING_AMMO_CLIP_PERCENT: Final[RTPCSourceType] = RTPCSourceType.REMAINING_AMMO_CLIP_PERCENT
VALUE: Final[RTPCSourceType] = RTPCSourceType.VALUE
