# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class State:
    Paused: ClassVar[State]  # native value: 2
    Running: ClassVar[State]  # native value: 1
    Stopped: ClassVar[State]  # native value: 0

Paused: Final[State] = State.Paused
Running: Final[State] = State.Running
Stopped: Final[State] = State.Stopped
