# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def ThreadPool(*args: Any, **kwargs: Any) -> Any: ...

internet: Any
reactor: Any
server: Any
wsgi: Any
