# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class Style:
    STYLE_LOOKAT: ClassVar[Style]  # native value: 5
    STYLE_LOOKAT_SCALEZ: ClassVar[Style]  # native value: 6
    STYLE_XYZ_SCALE: ClassVar[Style]  # native value: 0
    STYLE_XY_SCALE: ClassVar[Style]  # native value: 1
    STYLE_X_ROTATE: ClassVar[Style]  # native value: 2
    STYLE_Y_ROTATE: ClassVar[Style]  # native value: 3
    STYLE_Z_ROTATE: ClassVar[Style]  # native value: 4

STYLE_LOOKAT: Final[Style] = Style.STYLE_LOOKAT
STYLE_LOOKAT_SCALEZ: Final[Style] = Style.STYLE_LOOKAT_SCALEZ
STYLE_XYZ_SCALE: Final[Style] = Style.STYLE_XYZ_SCALE
STYLE_XY_SCALE: Final[Style] = Style.STYLE_XY_SCALE
STYLE_X_ROTATE: Final[Style] = Style.STYLE_X_ROTATE
STYLE_Y_ROTATE: Final[Style] = Style.STYLE_Y_ROTATE
STYLE_Z_ROTATE: Final[Style] = Style.STYLE_Z_ROTATE
