# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

class Waveform:
    SAWTOOTH: ClassVar[Waveform]  # native value: 3
    SINE: ClassVar[Waveform]  # native value: 2
    SQUARE: ClassVar[Waveform]  # native value: 0
    TRIANGLE: ClassVar[Waveform]  # native value: 1

SAWTOOTH: Final[Waveform] = Waveform.SAWTOOTH
SINE: Final[Waveform] = Waveform.SINE
SQUARE: Final[Waveform] = Waveform.SQUARE
TRIANGLE: Final[Waveform] = Waveform.TRIANGLE
