# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def GeneralWheelsAnimatorConfig(*args: Any, **kwargs: Any) -> Any: ...

@overload
def PhysicalDestroyedTrackConfig(arg0: Any) -> None: ...
@overload
def PhysicalDestroyedTrackConfig(arg0: Any, arg1: bool = ...) -> None: ...

def VehicleTracks(*args: Any, **kwargs: Any) -> Any: ...

def getDummyLodLink(arg0: Any = ...) -> Any: ...

BurnoutProcessor: Any
C11nAttachmentComponent: Any
C11nAttachmentEditComponent: Any
C11nComponent: Any
C11nEditComponent: Any
CollisionObstaclesCollector: Any
CompositeTrack: Any
DetailedEngineState: Any
DirtComponent: Any
FlagComponent: Any
FlyingInfoProvider: Any
FrictionAudition: Any
GearBox: Any
GeneralWheelsAnimator: Any
GunRecoilAnimator: Any
GunRotatorAudition: Any
LeveredSuspension: Final[int] = 8
LinkedNodesAnimator: Any
LodCalculator: Any
PhysicalTrack: Any
PhysicalTrackBuilder: Any
RecoilAnimator: Any
SiegeState: Any
SimpleTrack: Any
SplineTrack: Any
Suspension: Any
SuspensionSound: Any
SwingingAnimator: Any
TankWheelsAnimator: Any
TerrainMatKindSensor: Any
TessellationCollisionSensor: Any
TrackNodesAnimator: Any
VehicleAudition: Any
VehicleTraces: Any
WaterSensor: Any
