# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def ContinuousBurstEvent(arg0: Any, arg1: int, arg2: str, arg3: list[int] = ...) -> None: ...

def FireRateChangedEvent(arg0: Any, arg1: int, arg2: str, arg3: bool = ...) -> None: ...

def GeneralWheelsAnimatorConfig(*args: Any, **kwargs: Any) -> Any: ...

def MultiShotEvent(arg0: Any, arg1: int, arg2: str, arg3: int = ...) -> None: ...

def PhysicalDestroyedTrackConfig(arg0: Any) -> str: ...

def PhysicalTrackCreationData(arg0: Any, arg1: Any) -> None: ...

def SimpleTrackCreationData(arg0: Any, arg1: Any, arg2: Compound, arg3: Any) -> None: ...

def SingleShotEvent(*args: Any, **kwargs: Any) -> Any: ...

def SplineTrackCreationData(arg0: Any, arg1: Any, arg2: Compound, arg3: Any = ..., arg4: Any = ..., arg5: Any = ..., arg6: Any = ..., arg7: bool = ...) -> None: ...

def VariablesChangedEvent(arg0: Any, arg1: int, arg2: str, arg3: float = ...) -> None: ...

def VehicleTracksCreationContext(arg0: Any, arg1: bool, arg2: int, arg3: str, arg4: Any, arg5: Any, arg6: float = ...) -> None: ...

def getDummyLodLink(arg0: Any = ...) -> Any: ...

BurnoutProcessor: Any
C11nComponent: Any
C11nEditComponent: Any
CollisionObstaclesCollector: Any
CompositeTrack: Any
DetailedEngineState: Any
DetailedGunState: Any
DirtComponent: Any
FlagComponent: Any
FlyingInfoProvider: Any
FrictionAudition: Any
GearBox: Any
GeneralWheelsAnimator: Any
GeneralWheelsAnimatorSystem: Any
GunAudition: Any
GunInstallationComponent: Any
GunRotatorAudition: Any
LeveredSuspension: Final[int] = 8
LinkedNodesPitchAnimator: Any
LodCalculator: Any
OnPlayerInZoneComponent: Any
PhysicalTrackBuilder: Any
RecoilComponent: Any
RemainingAmmoClipPercentGetter: Any
SiegeState: Any
Suspension: Any
SuspensionSound: Any
SwingingAnimator: Any
TankWheelsAnimator: Any
TerrainMatKindSensor: Any
TerrainMatKindSensorSystem: Any
TessellationCollisionSensor: Any
TrackNodesAnimator: Any
VehicleAudition: Any
VehicleAuditionSystem: Any
VehicleSoundTriggerTarget: Any
VehicleTraces: Any
VehicleTracks: Any
WaterSensor: Any
