# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

WTAlwaysVisibleComponent: Any
WTCaptureLightningFilterComponent: Any
WTGeneratorProgressComponent: Any
WTGunReloadedComponent: Any
WTHealthComponent: Any
