# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

PyGuiApplication: Any
PyObjectArray: Any
PyObjectCommand: Any
PyObjectMap: Any
PyObjectView: Any
PyObjectViewModel: Any
PyObjectViewSettings: Any
PyObjectWindow: Any
PyObjectWindowSettings: Any
PyObjectWindowsArea: Any
Resource: Any
ValueType: Any
caseMap: Any
getDateFormat: Any
getImagePath: Any
getLayoutPath: Any
getNumberFormat: Any
getRealFormat: Any
getSoundEffectId: Any
getTimeFormat: Any
getTranslatedKey: Any
getTranslatedPluralText: Any
getTranslatedPluralTextByResId: Any
getTranslatedText: Any
getTranslatedTextByResId: Any
isTranslatedKeyValid: Any
isTranslatedTextExisted: Any
