# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

@overload
def Null(arg0: Any = ...) -> None: ...
@overload
def Null(arg0: Any = ..., arg1: int = ...) -> None: ...

def Str(*args: Any, **kwargs: Any) -> Any: ...

def foo(*args: Any, **kwargs: Any) -> Any: ...

def new(*args: Any, **kwargs: Any) -> Any: ...

__doc__: Any

class AgentStateBitMask:
    Null: ClassVar[AgentStateBitMask]  # native value: 0
    RoleInitialized: ClassVar[AgentStateBitMask]  # native value: 2
    Spawned: ClassVar[AgentStateBitMask]  # native value: 1

class InterruptionBitMask:
    BaseCapturingAlert: ClassVar[InterruptionBitMask]  # native value: 16
    CanNotShoot: ClassVar[InterruptionBitMask]  # native value: 2048
    CanShoot: ClassVar[InterruptionBitMask]  # native value: 1024
    CirclingTargetChanged: ClassVar[InterruptionBitMask]  # native value: 512
    CoverInvalidated: ClassVar[InterruptionBitMask]  # native value: 2
    GotShot: ClassVar[InterruptionBitMask]  # native value: 4
    MovementFailed: ClassVar[InterruptionBitMask]  # native value: 64
    Null: ClassVar[InterruptionBitMask]  # native value: 1
    ObservedByEnemy: ClassVar[InterruptionBitMask]  # native value: 8
    PushedByAnotherVehicle: ClassVar[InterruptionBitMask]  # native value: 128
    SavedPoThreatOnPathIncreasedsition: ClassVar[InterruptionBitMask]  # native value: 4096
    SnipePointInvalidated: ClassVar[InterruptionBitMask]  # native value: 32
    TargetChanged: ClassVar[InterruptionBitMask]  # native value: 256
    UndetectedMoveTargetInvalidated: ClassVar[InterruptionBitMask]  # native value: 8192

class PVEOverrideTargetingModes:
    LocalDirection: ClassVar[PVEOverrideTargetingModes]  # native value: 3
    Null: ClassVar[PVEOverrideTargetingModes]  # native value: 0
    WorldDirection: ClassVar[PVEOverrideTargetingModes]  # native value: 2
    WorldPosition: ClassVar[PVEOverrideTargetingModes]  # native value: 1

BaseCapturingAlert: Final[InterruptionBitMask] = InterruptionBitMask.BaseCapturingAlert
CanNotShoot: Final[InterruptionBitMask] = InterruptionBitMask.CanNotShoot
CanShoot: Final[InterruptionBitMask] = InterruptionBitMask.CanShoot
CirclingTargetChanged: Final[InterruptionBitMask] = InterruptionBitMask.CirclingTargetChanged
CoverInvalidated: Final[InterruptionBitMask] = InterruptionBitMask.CoverInvalidated
GotShot: Final[InterruptionBitMask] = InterruptionBitMask.GotShot
LocalDirection: Final[PVEOverrideTargetingModes] = PVEOverrideTargetingModes.LocalDirection
MovementFailed: Final[InterruptionBitMask] = InterruptionBitMask.MovementFailed
Null: Final[AgentStateBitMask] = AgentStateBitMask.Null
ObservedByEnemy: Final[InterruptionBitMask] = InterruptionBitMask.ObservedByEnemy
PushedByAnotherVehicle: Final[InterruptionBitMask] = InterruptionBitMask.PushedByAnotherVehicle
RoleInitialized: Final[AgentStateBitMask] = AgentStateBitMask.RoleInitialized
SavedPoThreatOnPathIncreasedsition: Final[InterruptionBitMask] = InterruptionBitMask.SavedPoThreatOnPathIncreasedsition
SnipePointInvalidated: Final[InterruptionBitMask] = InterruptionBitMask.SnipePointInvalidated
Spawned: Final[AgentStateBitMask] = AgentStateBitMask.Spawned
TargetChanged: Final[InterruptionBitMask] = InterruptionBitMask.TargetChanged
UndetectedMoveTargetInvalidated: Final[InterruptionBitMask] = InterruptionBitMask.UndetectedMoveTargetInvalidated
WorldDirection: Final[PVEOverrideTargetingModes] = PVEOverrideTargetingModes.WorldDirection
WorldPosition: Final[PVEOverrideTargetingModes] = PVEOverrideTargetingModes.WorldPosition
