# Generated by game-downloader from static native metadata; do not edit.
from typing import Any, ClassVar, Final, overload

def adler32(*args: Any, **kwargs: Any) -> Any: ...

def compress(*args: Any, **kwargs: Any) -> Any: ...

def compressobj(*args: Any, **kwargs: Any) -> Any: ...

def crc32(*args: Any, **kwargs: Any) -> Any: ...

def decompress(*args: Any, **kwargs: Any) -> Any: ...

def decompressobj(*args: Any, **kwargs: Any) -> Any: ...

DEFLATED: Final[int] = 8
DEF_MEM_LEVEL: Final[int] = 8
MAX_WBITS: Final[int] = 15
Z_DEFAULT_COMPRESSION: Final[int] = -1
Z_SYNC_FLUSH: Final[int] = 2
error: Any
