import os, tarfile, unittest, warnings, zipfile
from os.path import join
from textwrap import dedent
from test.test_support import captured_stdout, check_warnings, run_unittest
try:
    import zlib
except ImportError:
    zlib = None

try:
    import grp, pwd
    UID_GID_SUPPORT = True
except ImportError:
    UID_GID_SUPPORT = False

from distutils.command.sdist import sdist, show_formats
from distutils.core import Distribution
from distutils.tests.test_config import PyPIRCCommandTestCase
from distutils.errors import DistutilsOptionError
from distutils.spawn import find_executable
from distutils.log import WARN
from distutils.filelist import FileList
from distutils.archive_util import ARCHIVE_FORMATS
SETUP_PY = b"\nfrom distutils.core import setup\nimport somecode\n\nsetup(name='fake')\n"
MANIFEST = b'# file GENERATED by distutils, do NOT edit\nREADME\nbuildout.cfg\ninroot.txt\nsetup.py\ndata%(sep)sdata.dt\nscripts%(sep)sscript.py\nsome%(sep)sfile.txt\nsome%(sep)sother_file.txt\nsomecode%(sep)s__init__.py\nsomecode%(sep)sdoc.dat\nsomecode%(sep)sdoc.txt\n'

class SDistTestCase(PyPIRCCommandTestCase):

    def setUp(self):
        super(SDistTestCase, self).setUp()
        self.old_path = os.getcwd()
        os.mkdir(join(self.tmp_dir, b'somecode'))
        os.mkdir(join(self.tmp_dir, b'dist'))
        self.write_file((self.tmp_dir, b'README'), b'xxx')
        self.write_file((self.tmp_dir, b'somecode', b'__init__.py'), b'#')
        self.write_file((self.tmp_dir, b'setup.py'), SETUP_PY)
        os.chdir(self.tmp_dir)
        return

    def tearDown(self):
        os.chdir(self.old_path)
        super(SDistTestCase, self).tearDown()
        return

    def get_cmd(self, metadata=None):
        if metadata is None:
            metadata = {b'name': b'fake', b'version': b'1.0', b'url': b'xxx', b'author': b'xxx', b'author_email': b'xxx'}
        dist = Distribution(metadata)
        dist.script_name = b'setup.py'
        dist.packages = [b'somecode']
        dist.include_package_data = True
        cmd = sdist(dist)
        cmd.dist_dir = b'dist'
        return (dist, cmd)

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_prune_file_list(self):
        os.mkdir(join(self.tmp_dir, b'somecode', b'.svn'))
        self.write_file((self.tmp_dir, b'somecode', b'.svn', b'ok.py'), b'xxx')
        os.mkdir(join(self.tmp_dir, b'somecode', b'.hg'))
        self.write_file((self.tmp_dir, b'somecode', b'.hg',
         b'ok'), b'xxx')
        os.mkdir(join(self.tmp_dir, b'somecode', b'.git'))
        self.write_file((self.tmp_dir, b'somecode', b'.git',
         b'ok'), b'xxx')
        self.write_file((self.tmp_dir, b'somecode', b'.nfs0001'), b'xxx')
        dist, cmd = self.get_cmd()
        cmd.formats = [
         b'zip']
        cmd.ensure_finalized()
        cmd.run()
        dist_folder = join(self.tmp_dir, b'dist')
        files = os.listdir(dist_folder)
        self.assertEqual(files, [b'fake-1.0.zip'])
        zip_file = zipfile.ZipFile(join(dist_folder, b'fake-1.0.zip'))
        try:
            content = zip_file.namelist()
        finally:
            zip_file.close()

        expected = [
         12, 13, 14, 15, 
         16, 17]
        self.assertEqual(sorted(content), [b'fake-1.0/' + x for x in expected])
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_make_distribution(self):
        dist, cmd = self.get_cmd()
        cmd.formats = [
         b'gztar', b'tar']
        cmd.ensure_finalized()
        cmd.run()
        dist_folder = join(self.tmp_dir, b'dist')
        result = os.listdir(dist_folder)
        result.sort()
        self.assertEqual(result, [b'fake-1.0.tar', b'fake-1.0.tar.gz'])
        os.remove(join(dist_folder, b'fake-1.0.tar'))
        os.remove(join(dist_folder, b'fake-1.0.tar.gz'))
        cmd.formats = [
         b'tar', b'gztar']
        cmd.ensure_finalized()
        cmd.run()
        result = os.listdir(dist_folder)
        result.sort()
        self.assertEqual(result, [b'fake-1.0.tar', b'fake-1.0.tar.gz'])
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_unicode_metadata_tgz(self):
        dist, cmd = self.get_cmd({b'name': u'fake', b'version': u'1.0'})
        cmd.formats = [
         b'gztar']
        cmd.ensure_finalized()
        cmd.run()
        dist_folder = join(self.tmp_dir, b'dist')
        result = os.listdir(dist_folder)
        self.assertEqual(result, [b'fake-1.0.tar.gz'])
        os.remove(join(dist_folder, b'fake-1.0.tar.gz'))
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_add_defaults(self):
        dist, cmd = self.get_cmd()
        dist.package_data = {b'': [b'*.cfg', b'*.dat'], b'somecode': [
                       b'*.txt']}
        self.write_file((self.tmp_dir, b'somecode', b'doc.txt'), b'#')
        self.write_file((self.tmp_dir, b'somecode', b'doc.dat'), b'#')
        data_dir = join(self.tmp_dir, b'data')
        os.mkdir(data_dir)
        self.write_file((data_dir, b'data.dt'), b'#')
        some_dir = join(self.tmp_dir, b'some')
        os.mkdir(some_dir)
        hg_dir = join(self.tmp_dir, b'.hg')
        os.mkdir(hg_dir)
        self.write_file((hg_dir, b'last-message.txt'), b'#')
        self.write_file((self.tmp_dir, b'buildout.cfg'), b'#')
        self.write_file((self.tmp_dir, b'inroot.txt'), b'#')
        self.write_file((some_dir, b'file.txt'), b'#')
        self.write_file((some_dir, b'other_file.txt'), b'#')
        dist.data_files = [
         (
          b'data',
          [b'data/data.dt',
           b'buildout.cfg',
           b'inroot.txt',
           b'notexisting']),
         b'some/file.txt',
         b'some/other_file.txt']
        script_dir = join(self.tmp_dir, b'scripts')
        os.mkdir(script_dir)
        self.write_file((script_dir, b'script.py'), b'#')
        dist.scripts = [join(b'scripts', b'script.py')]
        cmd.formats = [
         b'zip']
        cmd.use_defaults = True
        cmd.ensure_finalized()
        cmd.run()
        dist_folder = join(self.tmp_dir, b'dist')
        files = os.listdir(dist_folder)
        self.assertEqual(files, [b'fake-1.0.zip'])
        zip_file = zipfile.ZipFile(join(dist_folder, b'fake-1.0.zip'))
        try:
            content = zip_file.namelist()
        finally:
            zip_file.close()

        expected = [
         3, 27, 28, 14, 
         29, 18, 15, 
         30, 
         31, 32, 
         33, 20, 21, 
         34, 
         35, 36, 
         37]
        self.assertEqual(sorted(content), [b'fake-1.0/' + x for x in expected])
        f = open(join(self.tmp_dir, b'MANIFEST'))
        try:
            manifest = f.read()
        finally:
            f.close()

        self.assertEqual(manifest, MANIFEST % {b'sep': (os.sep)})
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_metadata_check_option(self):
        dist, cmd = self.get_cmd(metadata={})
        cmd.ensure_finalized()
        cmd.run()
        warnings = [msg for msg in self.get_logs(WARN) if msg.startswith(b'warning: check:')]
        self.assertEqual(len(warnings), 2)
        self.clear_logs()
        dist, cmd = self.get_cmd()
        cmd.ensure_finalized()
        cmd.metadata_check = 0
        cmd.run()
        warnings = [msg for msg in self.get_logs(WARN) if msg.startswith(b'warning: check:')]
        self.assertEqual(len(warnings), 0)
        return

    def test_check_metadata_deprecated(self):
        dist, cmd = self.get_cmd()
        with check_warnings() as w:
            warnings.simplefilter(b'always')
            cmd.check_metadata()
            self.assertEqual(len(w.warnings), 1)
        return

    def test_show_formats(self):
        with captured_stdout() as stdout:
            show_formats()
        num_formats = len(ARCHIVE_FORMATS.keys())
        output = [line for line in stdout.getvalue().split(b'\n') if line.strip().startswith(b'--formats=')]
        self.assertEqual(len(output), num_formats)
        return

    def test_finalize_options(self):
        dist, cmd = self.get_cmd()
        cmd.finalize_options()
        self.assertEqual(cmd.manifest, b'MANIFEST')
        self.assertEqual(cmd.template, b'MANIFEST.in')
        self.assertEqual(cmd.dist_dir, b'dist')
        cmd.formats = 1
        self.assertRaises(DistutilsOptionError, cmd.finalize_options)
        cmd.formats = [b'zip']
        cmd.finalize_options()
        cmd.formats = b'supazipa'
        self.assertRaises(DistutilsOptionError, cmd.finalize_options)
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    @unittest.skipUnless(UID_GID_SUPPORT, b'Requires grp and pwd support')
    @unittest.skipIf(find_executable(b'tar') is None, b'The tar command is not found')
    @unittest.skipIf(find_executable(b'gzip') is None, b'The gzip command is not found')
    def test_make_distribution_owner_group(self):
        dist, cmd = self.get_cmd()
        cmd.formats = [
         b'gztar']
        cmd.owner = pwd.getpwuid(0)[0]
        cmd.group = grp.getgrgid(0)[0]
        cmd.ensure_finalized()
        cmd.run()
        archive_name = join(self.tmp_dir, b'dist', b'fake-1.0.tar.gz')
        archive = tarfile.open(archive_name)
        try:
            for member in archive.getmembers():
                self.assertEqual(member.uid, 0)
                self.assertEqual(member.gid, 0)

        finally:
            archive.close()

        dist, cmd = self.get_cmd()
        cmd.formats = [
         b'gztar']
        cmd.ensure_finalized()
        cmd.run()
        archive_name = join(self.tmp_dir, b'dist', b'fake-1.0.tar.gz')
        archive = tarfile.open(archive_name)
        try:
            for member in archive.getmembers():
                self.assertEqual(member.uid, os.getuid())

        finally:
            archive.close()

        return

    def _check_template(self, content):
        dist, cmd = self.get_cmd()
        os.chdir(self.tmp_dir)
        self.write_file(b'MANIFEST.in', content)
        cmd.ensure_finalized()
        cmd.filelist = FileList()
        cmd.read_template()
        warnings = self.get_logs(WARN)
        self.assertEqual(len(warnings), 1)
        return

    def test_invalid_template_unknown_command(self):
        self._check_template(b'taunt knights *')
        return

    def test_invalid_template_wrong_arguments(self):
        self._check_template(b'prune')
        return

    @unittest.skipIf(os.name != b'nt', b'test relevant for Windows only')
    def test_invalid_template_wrong_path(self):
        self._check_template(b'include examples/')
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_get_file_list(self):
        dist, cmd = self.get_cmd()
        dist.package_data = {b'somecode': [b'*.txt']}
        self.write_file((self.tmp_dir, b'somecode', b'doc.txt'), b'#')
        cmd.formats = [b'gztar']
        cmd.ensure_finalized()
        cmd.run()
        f = open(cmd.manifest)
        try:
            manifest = [line.strip() for line in f.read().split(b'\n') if line.strip() != b'']
        finally:
            f.close()

        self.assertEqual(len(manifest), 5)
        self.write_file((self.tmp_dir, b'somecode', b'doc2.txt'), b'#')
        build_py = dist.get_command_obj(b'build_py')
        build_py.finalized = False
        build_py.ensure_finalized()
        cmd.run()
        f = open(cmd.manifest)
        try:
            manifest2 = [line.strip() for line in f.read().split(b'\n') if line.strip() != b'']
        finally:
            f.close()

        self.assertEqual(len(manifest2), 6)
        self.assertIn(b'doc2.txt', manifest2[-1])
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_manifest_marker(self):
        dist, cmd = self.get_cmd()
        cmd.ensure_finalized()
        cmd.run()
        f = open(cmd.manifest)
        try:
            manifest = [line.strip() for line in f.read().split(b'\n') if line.strip() != b'']
        finally:
            f.close()

        self.assertEqual(manifest[0], b'# file GENERATED by distutils, do NOT edit')
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_manifest_comments(self):
        contents = dedent(b'            # bad.py\n            #bad.py\n            good.py\n            ')
        dist, cmd = self.get_cmd()
        cmd.ensure_finalized()
        self.write_file((self.tmp_dir, cmd.manifest), contents)
        self.write_file((self.tmp_dir, b'good.py'), b'# pick me!')
        self.write_file((self.tmp_dir, b'bad.py'), b"# don't pick me!")
        self.write_file((self.tmp_dir, b'#bad.py'), b"# don't pick me!")
        cmd.run()
        self.assertEqual(cmd.filelist.files, [b'good.py'])
        return

    @unittest.skipUnless(zlib, b'requires zlib')
    def test_manual_manifest(self):
        dist, cmd = self.get_cmd()
        cmd.formats = [b'gztar']
        cmd.ensure_finalized()
        self.write_file((self.tmp_dir, cmd.manifest), b'README.manual')
        self.write_file((self.tmp_dir, b'README.manual'), b'This project maintains its MANIFEST file itself.')
        cmd.run()
        self.assertEqual(cmd.filelist.files, [b'README.manual'])
        f = open(cmd.manifest)
        try:
            manifest = [line.strip() for line in f.read().split(b'\n') if line.strip() != b'']
        finally:
            f.close()

        self.assertEqual(manifest, [b'README.manual'])
        archive_name = join(self.tmp_dir, b'dist', b'fake-1.0.tar.gz')
        archive = tarfile.open(archive_name)
        try:
            filenames = [tarinfo.name for tarinfo in archive]
        finally:
            archive.close()

        self.assertEqual(sorted(filenames), [b'fake-1.0', b'fake-1.0/PKG-INFO',
         b'fake-1.0/README.manual'])
        return


def test_suite():
    return unittest.makeSuite(SDistTestCase)


if __name__ == b'__main__':
    run_unittest(test_suite())
