from collections import defaultdict
from random import randint, uniform
rewardGroups = [
 {b'start_position': 1, 
    b'end_position': 5, 
    b'group_type': 1, 
    b'rewards_by_position': {1: [{b'item_icon': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', b'item_count': 3}, {b'item_icon': b'../maps/icons/quests/bonuses/small/aimingStabilizer.png', b'item_count': 2}, {b'item_icon': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', b'item_count': 1}], 2: [{b'item_icon': b'../maps/icons/quests/bonuses/small/autoExtinguishers.png', b'item_count': 4}, {b'item_icon': b'../maps/icons/quests/bonuses/small/berths.png', b'item_count': 5}, {b'item_icon': b'../maps/icons/quests/bonuses/small/booster_credits.png', b'item_count': 6}], 3: [{b'item_icon': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', b'item_count': 7}, {b'item_icon': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', b'item_count': 8}, {b'item_icon': b'../maps/icons/quests/bonuses/small/booster_xp.png', b'item_count': 9}], 4: [{b'item_icon': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', b'item_count': 4}, {b'item_icon': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', b'item_count': 5}, {b'item_icon': b'../maps/icons/quests/bonuses/small/booster_xp.png', b'item_count': 6}], 5: [{b'item_icon': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', b'item_count': 1}, {b'item_icon': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', b'item_count': 2}, {b'item_icon': b'../maps/icons/quests/bonuses/small/booster_xp.png', b'item_count': 3}]}},
 {b'start_position': 6, 
    b'end_position': 20, 
    b'group_type': 2, 
    b'rewards_by_group': [{b'item_icon': b'../maps/icons/quests/bonuses/small/camouflageNet.png', b'item_count': 1}, {b'item_icon': b'../maps/icons/quests/bonuses/small/camouflages.png', b'item_count': 2}]},
 {b'start_position': 21, 
    b'end_position': 30, 
    b'group_type': 3, 
    b'rewards_by_group': [{b'item_icon': b'../maps/icons/quests/bonuses/small/chocolate.png', b'item_count': 1}, {b'item_icon': b'../maps/icons/quests/bonuses/small/coatedOptics.png', b'item_count': 2}, {b'item_icon': b'../maps/icons/quests/bonuses/small/cocacola.png', b'item_count': 3}]},
 {b'start_position': 31, 
    b'end_position': 1000, 
    b'group_type': 5}]
myLeaderboardInfo = {0: {b'rank': 1, 
       b'p1': 99999, 
       b'p2': (randint(100, 9999)), 
       b'p3': (randint(100, 9999)), 
       b'page_number': 1, 
       b'is_inside_viewsize': True, 
       b'last_in_leaderboard_value': 1024, 
       b'battles_count': 1024}, 
   1: {b'rank': 3, 
       b'p1': 99001, 
       b'p2': (randint(100, 9999)), 
       b'p3': (randint(100, 9999)), 
       b'page_number': 1, 
       b'is_inside_viewsize': True, 
       b'last_in_leaderboard_value': 1024, 
       b'battles_count': 998}, 
   2: {b'rank': 12, 
       b'p1': 5555, 
       b'p2': (randint(100, 9999)), 
       b'p3': (randint(100, 9999)), 
       b'page_number': 1, 
       b'is_inside_viewsize': True, 
       b'last_in_leaderboard_value': 1024, 
       b'battles_count': 440}, 
   3: {b'rank': 55, 
       b'p1': 3421, 
       b'p2': (randint(100, 9999)), 
       b'p3': (randint(100, 9999)), 
       b'page_number': 2, 
       b'is_inside_viewsize': True, 
       b'last_in_leaderboard_value': 1024, 
       b'battles_count': 100}, 
   4: {b'rank': 666, 
       b'p1': 1300, 
       b'p2': (randint(100, 9999)), 
       b'p3': (randint(100, 9999)), 
       b'page_number': 14, 
       b'is_inside_viewsize': True, 
       b'last_in_leaderboard_value': 1024, 
       b'battles_count': 10}, 
   5: {b'rank': None, 
       b'p1': 100, 
       b'p2': (randint(100, 9999)), 
       b'p3': (randint(100, 9999)), 
       b'page_number': None, 
       b'is_inside_viewsize': False, 
       b'last_in_leaderboard_value': 1024, 
       b'battles_count': 5}}
userNamesForLB = [
 62, 
 63, 
 64, 
 65, 
 66, 
 67, 
 68, 
 69, 
 70, 
 71, 
 72, 
 73, 
 74, 
 75, 
 76, 
 77, 
 78, 
 79, 
 80]
userClanTagForLB = [
 81, 
 82, 
 83, 
 84, 
 85, 
 86, 
 87, 
 88, 
 89, 
 90, 
 91, 
 92, 
 93, 
 94, 
 95, 
 96, 
 97, 
 98, 
 99, 
 100]
cdUSA = [
 101, 
 102, 
 103, 
 104, 
 105, 
 106, 
 107, 
 108, 
 109, 
 110, 
 111]
cdUSSR = [
 112, 
 113, 
 114, 
 115, 
 116, 
 117, 
 118, 
 119, 
 120, 
 121, 
 122, 
 123, 
 124, 
 125, 
 126, 
 127, 
 128, 
 129, 
 130, 
 131]
cdGER = [
 3, 
 132, 
 133, 
 134, 
 135, 
 136, 
 137, 
 138]
cdFRA = [
 139, 
 140, 
 141, 
 142, 
 143, 
 144, 
 145, 
 146]
cdCH = [
 147, 
 148, 
 149, 
 150, 
 151, 
 152, 
 153, 
 154, 
 155]
cdJP = [
 3681,
 39265,
 3937]
cdLongNameTank = [
 159, 
 160, 
 142, 
 161, 
 162]
userClanTagColorForLB = [
 163, 
 164, 
 165, 
 166, 
 167, 
 168, 
 169, 
 170, 
 171, 
 172, 
 173]
availableNationVeh = [
 cdUSA, cdUSSR, cdGER, cdFRA, cdCH, cdJP]
leaderboardMockRequest = {b'value': None}

def makeLeaderboard(vNation):
    playersData = []
    playersDataSumAll = []
    leaderboardData = []
    leaderboardDataSumAll = []
    for i in range(1000):
        playersData.append({b'rank': (i + 1), 
           b'spa_id': i, 
           b'name': (getRandomValue(userNamesForLB) + str(i)), 
           b'clan_tag': (getRandomValue(userClanTagForLB)), 
           b'clan_color': (str(getRandomValue(userClanTagColorForLB))), 
           b'p1': (randint(100, 99999)), 
           b'p2': (randint(100, 99999)), 
           b'p3': (randint(100, 99999)), 
           b'info': [
                   {b'battle_ts': 1503363600, 
                      b'vehicle_cd': (getRandomValue(vNation)), 
                      b'battle_result': b'win', 
                      b'is_in_squad': True, 
                      b'exp': (randint(1000, 99999)), 
                      b'damage': (randint(100, 99999)), 
                      b'assisted_damage': (randint(100, 99999)), 
                      b'frags': (randint(0, 15)), 
                      b'blocked_damage': (randint(100, 99999))},
                   {b'battle_ts': 1503363600, 
                      b'vehicle_cd': (getRandomValue(vNation)), 
                      b'battle_result': b'loss', 
                      b'is_in_squad': False, 
                      b'exp': (randint(1000, 99999)), 
                      b'damage': (randint(100, 99999)), 
                      b'assisted_damage': (randint(100, 99999)), 
                      b'frags': (randint(0, 15)), 
                      b'blocked_damage': (randint(100, 99999))},
                   {b'battle_ts': 1503363600, 
                      b'vehicle_cd': (getRandomValue(vNation)), 
                      b'battle_result': b'win', 
                      b'is_in_squad': True, 
                      b'exp': (randint(1000, 99999)), 
                      b'damage': (randint(100, 99999)), 
                      b'assisted_damage': (randint(100, 99999)), 
                      b'frags': (randint(0, 15)), 
                      b'blocked_damage': (randint(100, 99999))},
                   {b'battle_ts': 1500634215, 
                      b'vehicle_cd': (getRandomValue(vNation)), 
                      b'battle_result': b'loss', 
                      b'is_in_squad': False, 
                      b'exp': (randint(1000, 99999)), 
                      b'damage': (randint(100, 99999)), 
                      b'assisted_damage': (randint(100, 99999)), 
                      b'frags': (randint(0, 15)), 
                      b'blocked_damage': (randint(100, 99999))},
                   {b'battle_ts': 1500634215, 
                      b'vehicle_cd': (getRandomValue(vNation)), 
                      b'battle_result': b'loss', 
                      b'is_in_squad': False, 
                      b'exp': (randint(1000, 99999)), 
                      b'damage': (randint(100, 99999)), 
                      b'assisted_damage': (randint(100, 99999)), 
                      b'frags': (randint(0, 15)), 
                      b'blocked_damage': (randint(100, 99999))}]})
        playersDataSumAll.append({b'rank': (i + 1), 
           b'spa_id': i, 
           b'name': (getRandomValue(userNamesForLB) + str(i)), 
           b'clan_tag': (getRandomValue(userClanTagForLB)), 
           b'clan_color': (str(getRandomValue(userClanTagColorForLB))), 
           b'p1': (randint(100, 9999)), 
           b'p2': (randint(100, 9999)), 
           b'p3': (randint(100, 9999)), 
           b'info': [
                   {b'avg_exp': (randint(100, 99999)), 
                      b'avg_damage_dealt': (randint(100, 99999)), 
                      b'avg_damage_assisted': (randint(100, 99999)), 
                      b'win_rate': (uniform(30, 70))},
                   {b'avg_exp': (randint(100, 99999)), 
                      b'avg_damage_dealt': (randint(100, 99999)), 
                      b'avg_damage_assisted': (randint(100, 99999)), 
                      b'win_rate': (uniform(30, 70))},
                   {b'avg_exp': (randint(100, 99999)), 
                      b'avg_damage_dealt': (randint(100, 99999)), 
                      b'avg_damage_assisted': (randint(100, 99999)), 
                      b'win_rate': (uniform(30, 70))},
                   {b'avg_exp': (randint(100, 99999)), 
                      b'avg_damage_dealt': (randint(100, 99999)), 
                      b'avg_damage_assisted': (randint(100, 99999)), 
                      b'win_rate': (uniform(30, 70))},
                   {b'avg_exp': (randint(100, 99999)), 
                      b'avg_damage_dealt': (randint(100, 99999)), 
                      b'avg_damage_assisted': (randint(100, 99999)), 
                      b'win_rate': (uniform(30, 70))}]})

    for page in range(50):
        leaderboardData.append({b'meta': {b'page_number': (page + 1), 
                     b'pages_amount': 20, 
                     b'rewards': [{b'reward_category_number': 1, b'page_number': 1}, {b'reward_category_number': 2, b'page_number': 1}, {b'reward_category_number': 3, b'page_number': 2}, {b'reward_category_number': 4, b'page_number': 3}], b'recalculation_interval': 3600, 
                     b'last_leaderboard_recalculation_ts': 1501156127, 
                     b'next_leaderboard_recalculation_ts': 1501242527}, 
           b'data': []})
        leaderboardDataSumAll.append({b'meta': {b'page_number': (page + 1), 
                     b'pages_amount': 20, 
                     b'rewards': [{b'reward_category_number': 1, b'page_number': 1}, {b'reward_category_number': 2, b'page_number': 1}, {b'reward_category_number': 3, b'page_number': 2}, {b'reward_category_number': 4, b'page_number': 3}], b'recalculation_interval': 3600, 
                     b'last_leaderboard_recalculation_ts': 1501156127, 
                     b'next_leaderboard_recalculation_ts': 1501242527}, 
           b'data': []})

    for idx, player in enumerate(playersData):
        leaderboardData[idx / 50][b'data'].append(player)

    for idx, player in enumerate(playersDataSumAll):
        leaderboardDataSumAll[idx / 50][b'data'].append(player)
        return (
         leaderboardData, leaderboardDataSumAll)

    return


def getRandomValue(source):
    return source[randint(0, len(source) - 1)]


LeaderboardsData = defaultdict(dict)
indx = 0
for nation in availableNationVeh:
    lbd, lbdsa = makeLeaderboard(nation)
    LeaderboardsData[indx][b'leaderboardData'] = lbd
    LeaderboardsData[indx][b'leaderboardDataSumAll'] = lbdsa
    indx += 1

eventPlayerData = {b'all_battles_count': 12345, 
   b'win_rate': 46.4, 
   b'events_list': [
                  {b'event_id': b'1', 
                     b'player_state': 1, 
                     b'player_state_reasons': [], b'players_in_event': 1000, 
                     b'can_join': False}]}
hangarFlagData = [
 {b'event_id': b'1', 
    b'is_registered': True}]
eventMyTop = {b'meta': {b'recalculation_interval': 3600, 
             b'last_leaderboard_recalculation_ts': 1502360027, 
             b'next_leaderboard_recalculation_ts': 1502370027}, 
   b'data': [
           {b'leaderboard_id': 0, 
              b'my_position': 1, 
              b'battles_count': 1024, 
              b'my_value': 99999, 
              b'last_in_leaderboard_value': 1024},
           {b'leaderboard_id': 1, 
              b'my_position': 3, 
              b'battles_count': 998, 
              b'my_value': 99001, 
              b'last_in_leaderboard_value': 1024},
           {b'leaderboard_id': 2, 
              b'my_position': 12, 
              b'battles_count': 440, 
              b'my_value': 5555, 
              b'last_in_leaderboard_value': 1024},
           {b'leaderboard_id': 3, 
              b'my_position': 55, 
              b'battles_count': 100, 
              b'my_value': 3421, 
              b'last_in_leaderboard_value': 1024},
           {b'leaderboard_id': 4, 
              b'my_position': 666, 
              b'battles_count': 10, 
              b'my_value': 1300, 
              b'last_in_leaderboard_value': 1024},
           {b'leaderboard_id': 5, 
              b'my_position': None, 
              b'battles_count': 5, 
              b'my_value': 100, 
              b'last_in_leaderboard_value': 1024}]}
eventEventsData = [
 {b'event_id': b'1', 
    b'name': b'\xd0\x9c\xd0\xb0\xd1\x80\xd1\x88 \xd0\xbd\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb9', 
    b'type': b'nation', 
    b'leaderboard_view_size': 1000, 
    b'publish_date': b'', 
    b'start_date': b'2017-07-10T10:15:00', 
    b'participants_freeze_deadline': b'2017-09-29T10:15:00', 
    b'end_date': b'2017-09-30T10:15:00', 
    b'rewarding_date': b'2017-12-30T10:15:00', 
    b'manual': b'', 
    b'is_squad_allowed': False, 
    b'battle_type': 1, 
    b'prime_times': [
                   {b'server': b'0', 
                      b'start_time': b'01:00:00', 
                      b'end_time': b'23:00:00'},
                   {b'server': b'201', 
                      b'start_time': b'01:00:00', 
                      b'end_time': b'23:00:00'},
                   {b'server': b'202', 
                      b'start_time': b'01:00:00', 
                      b'end_time': b'23:00:00'},
                   {b'server': b'101', 
                      b'start_time': b'01:00:00', 
                      b'end_time': b'02:00:00'},
                   {b'server': b'102', 
                      b'start_time': b'01:00:00', 
                      b'end_time': b'02:00:00'}], 
    b'objective_parameter': b'damageDealt', 
    b'additional_sorting_parameter': b'', 
    b'informational_parameter': b'', 
    b'method': b'max', 
    b'cardinality': 5, 
    b'limits': {b'win_rate_min': 26.4, 
                b'win_rate_max': 66.4, 
                b'registration_date_max': b'2017-07-10T10:21:00', 
                b'is_registration_needed': True, 
                b'battles_count_min': 1, 
                b'vehicles': [{b'leaderboard_id': 0, b'vehicles': cdUSA}, {b'leaderboard_id': 1, b'vehicles': cdUSSR}, {b'leaderboard_id': 2, b'vehicles': cdGER}, {b'leaderboard_id': 3, b'vehicles': cdFRA}, {b'leaderboard_id': 4, b'vehicles': cdCH}, {b'leaderboard_id': 5, b'vehicles': cdJP}], b'nations': [{b'leaderboard_id': 0, b'nation': b'usa'}, {b'leaderboard_id': 1, b'nation': b'ussr'}, {b'leaderboard_id': 2, b'nation': b'germany'}, {b'leaderboard_id': 3, b'nation': b'france'}, {b'leaderboard_id': 4, b'nation': b'china'}, {b'leaderboard_id': 5, b'nation': b'japan'}, {b'leaderboard_id': 6, b'nation': b'czech'}, {b'leaderboard_id': 7, b'nation': b'uk'}, {b'leaderboard_id': 8, b'nation': b'poland'}, {b'leaderboard_id': 9, b'nation': b'sweden'}], b'vehicles_levels': [{b'leaderboard_id': 0, b'level': 5}, {b'leaderboard_id': 1, b'level': 6}, {b'leaderboard_id': 2, b'level': 7}, {b'leaderboard_id': 3, b'level': 8}, {b'leaderboard_id': 4, b'level': 9}, {b'leaderboard_id': 5, b'level': 10}], b'vehicles_classes': [{b'leaderboard_id': 0, b'class': b'heavyTank'}, {b'leaderboard_id': 1, b'class': b'mediumTank'}, {b'leaderboard_id': 2, b'class': b'lightTank'}, {b'leaderboard_id': 3, b'class': b'AT-SPG'}, {b'leaderboard_id': 4, b'class': b'SPG'}]}, 
    b'rewards_by_rank': [
                       {b'leaderboard_id': 0, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/aimingStabilizer.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 1}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 2, 
                                              b'rank_max': 2, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/autoExtinguishers.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/berths.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_credits.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 3, 
                                              b'rank_max': 3, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 7},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 8},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 9}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 4, 
                                              b'rank_max': 4, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 5, 
                                              b'rank_max': 5, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 6, 
                                              b'rank_max': 6, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflageNet.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflages.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 7, 
                                              b'rank_max': 7, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/chocolate.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/coatedOptics.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/cocacola.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 8, 
                                              b'rank_max': 8, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/combatPayments.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/credits.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crew.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 9, 
                                              b'rank_max': 9, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crystal.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/default.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/emblems.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 10, 
                                              b'rank_max': 10, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/enhancedAimDrives.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/exp.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 1, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/aimingStabilizer.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 1}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 2, 
                                              b'rank_max': 2, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/autoExtinguishers.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/berths.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_credits.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 3, 
                                              b'rank_max': 3, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 7},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 8},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 9}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 4, 
                                              b'rank_max': 4, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 5, 
                                              b'rank_max': 5, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 6, 
                                              b'rank_max': 6, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflageNet.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflages.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 7, 
                                              b'rank_max': 7, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/chocolate.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/coatedOptics.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/cocacola.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 8, 
                                              b'rank_max': 8, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/combatPayments.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/credits.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crew.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 9, 
                                              b'rank_max': 9, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crystal.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/default.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/emblems.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 10, 
                                              b'rank_max': 10, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/enhancedAimDrives.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/exp.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 2, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/aimingStabilizer.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 1}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 2, 
                                              b'rank_max': 2, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/autoExtinguishers.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/berths.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_credits.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 3, 
                                              b'rank_max': 3, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 7},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 8},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 9}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 4, 
                                              b'rank_max': 4, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 5, 
                                              b'rank_max': 5, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 6, 
                                              b'rank_max': 6, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflageNet.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflages.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 7, 
                                              b'rank_max': 7, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/chocolate.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/coatedOptics.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/cocacola.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 8, 
                                              b'rank_max': 8, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/combatPayments.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/credits.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crew.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 9, 
                                              b'rank_max': 9, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crystal.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/default.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/emblems.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 10, 
                                              b'rank_max': 10, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/enhancedAimDrives.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/exp.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 3, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/aimingStabilizer.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 1}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 2, 
                                              b'rank_max': 2, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/autoExtinguishers.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/berths.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_credits.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 3, 
                                              b'rank_max': 3, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 7},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 8},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 9}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 4, 
                                              b'rank_max': 4, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 5, 
                                              b'rank_max': 5, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 6, 
                                              b'rank_max': 6, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflageNet.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflages.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 7, 
                                              b'rank_max': 7, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/chocolate.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/coatedOptics.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/cocacola.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 8, 
                                              b'rank_max': 8, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/combatPayments.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/credits.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crew.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 9, 
                                              b'rank_max': 9, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crystal.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/default.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/emblems.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 10, 
                                              b'rank_max': 10, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/enhancedAimDrives.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/exp.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 4, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/aimingStabilizer.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 1}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 2, 
                                              b'rank_max': 2, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/autoExtinguishers.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/berths.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_credits.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 3, 
                                              b'rank_max': 3, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 7},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 8},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 9}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 4, 
                                              b'rank_max': 4, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 5, 
                                              b'rank_max': 5, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 6, 
                                              b'rank_max': 6, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflageNet.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflages.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 7, 
                                              b'rank_max': 7, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/chocolate.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/coatedOptics.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/cocacola.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 8, 
                                              b'rank_max': 8, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/combatPayments.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/credits.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crew.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 9, 
                                              b'rank_max': 9, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crystal.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/default.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/emblems.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 10, 
                                              b'rank_max': 10, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/enhancedAimDrives.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/exp.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 5, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/aimingStabilizer.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 1}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 2, 
                                              b'rank_max': 2, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/autoExtinguishers.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/berths.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_credits.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 3, 
                                              b'rank_max': 3, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 7},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 8},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 9}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 4, 
                                              b'rank_max': 4, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 4},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 5},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 6}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 5, 
                                              b'rank_max': 5, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_crew_xp.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_free_xp.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/booster_xp.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 6, 
                                              b'rank_max': 6, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflageNet.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/camouflages.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 7, 
                                              b'rank_max': 7, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/chocolate.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/coatedOptics.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/cocacola.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 8, 
                                              b'rank_max': 8, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/combatPayments.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/credits.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crew.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 9, 
                                              b'rank_max': 9, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/crystal.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/default.png', 
                                                            b'rewards_amount': 2},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/emblems.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 10, 
                                              b'rank_max': 10, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/enhancedAimDrives.png', 
                                                            b'rewards_amount': 1},
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/exp.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 6, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 7, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 8, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]},
                       {b'leaderboard_id': 9, 
                          b'reward_groups': [
                                           {b'reward_category_number': 1, 
                                              b'rank_min': 1, 
                                              b'rank_max': 1, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/additionalBriefing.png', 
                                                            b'rewards_amount': 3}]},
                                           {b'reward_category_number': 2, 
                                              b'rank_min': 11, 
                                              b'rank_max': 50, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 3, 
                                              b'rank_min': 51, 
                                              b'rank_max': 100, 
                                              b'rewards': [
                                                         {b'reward_type': b'../maps/icons/quests/bonuses/small/antifragmentationLining.png', 
                                                            b'rewards_amount': 2}]},
                                           {b'reward_category_number': 4, 
                                              b'rank_min': 101, 
                                              b'rank_max': 1000, 
                                              b'rewards': []}]}]}]
