from __future__ import absolute_import
from FairplayVehicleBattleStatsComponent import FairplayVehicleBattleStatsComponent

class HWFairplayVehicleBattleStatsComponent(FairplayVehicleBattleStatsComponent):
    pass
