import httplib
REQUEST_TIMEOUT = 30.0
POLLING_PERIOD = 1.0
POLLING_REQUEST_TIMEOUT = 15.0
SOLVE_POW_TIMEOUT = 15.0
CONTENT_WAITING = b'loadContent'
ACCEPTED_HTTP_CODES = (
 httplib.OK, httplib.CREATED)
