const fs = require('fs');
const path = require('path');

const GLOBAL_STYLES_DIR = path.resolve(__dirname, '../../src/global-styles');
const OUTPUT_DIR = path.resolve(__dirname, '../../_dev/generated_ide_style_helper');
const VARIABLES_DIR = path.join(GLOBAL_STYLES_DIR, 'variables');
const MIXINS_DIR = path.join(GLOBAL_STYLES_DIR, 'mixins');

const AUTO_GENERATED_HEADER = '// AUTO-GENERATED by generate_ide_style_helper.js — do not edit manually\n\n';
const SENTINEL = '__SENTINEL__';

function getSourceFiles(dir) {
    return fs.readdirSync(dir).filter((f) => f.endsWith('.js') && f !== 'index.js');
}

function toScssFilename(jsFilename) {
    return `_${path.basename(jsFilename, '.js')}.scss`;
}

function loadAllVariables() {
    const allVars = {};
    for (const file of getSourceFiles(VARIABLES_DIR)) {
        Object.assign(allVars, require(path.join(VARIABLES_DIR, file)));
    }
    return allVars;
}

function resolveScssDefault(value, allVars) {
    if (typeof value === 'string' && /^#[0-9A-Fa-f]{3,8}$/.test(value)) {
        const entry = Object.entries(allVars).find(([, v]) => v === value);
        if (entry) {
            return `$${entry[0]}`;
        }
    }
    return value ?? 'null';
}

function extractParamName(fn) {
    const match = fn.toString().match(/\(\s*_\s*,\s*(\w+)/);
    return match ? match[1] : null;
}

/**
 * Calls the mixin with defaults and with a sentinel value to detect
 * which CSS properties are controlled by the mixin's argument.
 * Returns null for PostCSS mixins that require a real node to execute.
 */
function introspectMixin(fn) {
    let defaultStyles;
    try {
        defaultStyles = fn();
    } catch {
        return null;
    }

    if (!defaultStyles || typeof defaultStyles !== 'object' || Array.isArray(defaultStyles)) {
        return null;
    }

    let sentinelStyles;
    try {
        sentinelStyles = fn(null, SENTINEL);
    } catch {
        return { styles: defaultStyles, paramProps: [], paramName: null };
    }

    const paramProps = Object.keys(sentinelStyles).filter((prop) => sentinelStyles[prop] === SENTINEL);
    return { styles: defaultStyles, paramProps, paramName: extractParamName(fn) };
}

function generateVariablesScss(obj) {
    let scss = AUTO_GENERATED_HEADER;
    for (const [key, value] of Object.entries(obj)) {
        if (typeof value === 'string' || typeof value === 'number') {
            scss += `$${key}: ${value};\n`;
        }
    }
    return scss;
}

function generateMixinsScss(mixinsObj, allVars) {
    let scss = AUTO_GENERATED_HEADER;
    let hasContent = false;

    for (const [name, value] of Object.entries(mixinsObj)) {
        if (typeof value === 'string') {
            scss += `@mixin ${value}() {\n  @content;\n}\n\n`;
            hasContent = true;
            continue;
        }

        if (typeof value !== 'function') {
            continue;
        }

        const info = introspectMixin(value);
        if (!info) {
            continue;
        }
        hasContent = true;

        const { styles, paramProps, paramName } = info;

        if (paramProps.length > 0 && paramName) {
            const argName = `$${paramName}`;
            const resolvedDefault = resolveScssDefault(styles[paramProps[0]], allVars);

            scss += `@mixin ${name}(${argName}: ${resolvedDefault}) {\n`;
            for (const [prop, val] of Object.entries(styles)) {
                scss += `  ${prop}: ${paramProps.includes(prop) ? argName : val};\n`;
            }
        } else {
            scss += `@mixin ${name}() {\n`;
            for (const [prop, val] of Object.entries(styles)) {
                scss += `  ${prop}: ${val};\n`;
            }
        }

        scss += `}\n\n`;
    }

    return hasContent ? scss : null;
}

// ===== RUN =====

fs.rmSync(OUTPUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const allVars = loadAllVariables();

for (const file of getSourceFiles(VARIABLES_DIR)) {
    const exports = require(path.join(VARIABLES_DIR, file));
    fs.writeFileSync(path.join(OUTPUT_DIR, toScssFilename(file)), generateVariablesScss(exports));
}

for (const file of getSourceFiles(MIXINS_DIR)) {
    const exports = require(path.join(MIXINS_DIR, file));
    const content = generateMixinsScss(exports, allVars);
    if (content) {
        fs.writeFileSync(path.join(OUTPUT_DIR, toScssFilename(file)), content);
    }
}

// eslint-disable-next-line no-console
console.log('\x1b[32m%s\x1b[0m', 'Generated IDE style helper successfully built');
