class XML_NAME_SPACE(object):
    BLOCKING_CMD = b'urn:xmpp:blocking'
    CHAT_STATES = b'http://jabber.org/protocol/chatstates'
    DELAY = b'urn:xmpp:delay'
    STANZA_ERROR = b'urn:ietf:params:xml:ns:xmpp-stanzas'
    RESULT_SET_MANAGEMENT = b'http://jabber.org/protocol/rsm'
    DISCO_ITEMS = b'http://jabber.org/protocol/disco#items'
    DISCO_INFO = b'http://jabber.org/protocol/disco#info'
    MUC_OWNER = b'http://jabber.org/protocol/muc#owner'
    DATA_FORMS = b'jabber:x:data'
    EXTENSION = b'http://lesta.ru/xmpp#v2'
    EXTENSION_EXTRA = b'http://lesta.ru/xmpp#extra-attributes'
    EXT_CLIENT = b'http://lesta.ru/xmpp#client'
    SPA_RESOLVER = b'http://lesta.ru/xmpp#spa-resolver'
    EXT_STORAGE = b'http://lesta.ru/xmpp#storage'
    PRIVATE_HISTORY = b'http://lesta.ru/xmpp#private-message-history'
    MESSAGE_ID = b'http://lesta.ru/xmpp#message-id'
    EXT_MUC_ROOMS = b'http://lesta.ru/xmpp#filter-muc-rooms-disco'
    EXT_DISCO_ITEMS = b'http://lesta.ru/xmpp#disco#items:exts'


class XML_TAG_NAME(object):
    BLOCK_LIST = b'blocklist'
    BLOCK_ITEM = b'block'
    UNBLOCK_ITEM = b'unblock'
    MESSAGE = b'message'
    DELAY = b'delay'
    QUERY = b'query'
    LIST = b'list'
    ITEM = b'item'
    ERROR = b'error'
    SET = b'set'
    FILTER = b'filter'
    CRITERION = b'criterion'
    X = b'x'
    FIELD = b'field'
    VALUE = b'value'
    IDENTITY = b'identity'
    FEATURE = b'feature'
    CREATED_BY = b'created-by'
    EXTENSION = b'exts'
    EXT_CLIENT = b'exts-client'
    PRIVATE_HISTORY = b'private-history'
    MESSAGE_ID = b'message-id'
    NICKNAME_PREFIX_SEARCH = b'nickname-prefix-search'
    MUC_PRIVILEGES = b'muc-privileges'
    EXTENSION_EXTRA = b'extra'
